internal/provider/resource_consul_cluster.go
internal/provider/validators.go
internal/provider/validators_test.go

While updating some of the HCP Consul E2E tests to use the new provider, I noticed that we were not validating that the Consul cluster `datacenter` does not contain uppercase letters. 
This PR validates the `datacenter` as such, as well as cleans up some comments.

Validate Consul datacenter and lowercase the default

---

docs/guides/consul-root-token.md
docs/guides/peering.md
docs/guides/quick-start.md
docs/index.md
examples/guides/quick_start/main.tf
examples/provider/provider.tf
internal/provider/provider.go
templates/guides/peering.md.tmpl

Fixes this line in the Peering guide:
Which should look like:
Also adds up-to-date generated docs, looks like one of the last cleanup PRs missed them.

fix peering guide note + missed generated docs

---

internal/provider/resource_aws_network_peering.go
internal/provider/resource_consul_cluster.go
internal/provider/resource_consul_snapshot.go
internal/provider/resource_hvn.go

Set the `ID` of resources that need to poll for an operation _before_ polling the operation. This prevents the case where a resource is created in the DB but the async resource operation fails and Terraform has no state entry so it thinks the resource does not exist (even though it does and is in a failed state), so the user can't run `terraform destroy` to clean up the failed resource.
This PR also sets the Terraform `ID` of resources  in a failed state to `""` during read. This allows HCP resources (ie a Consul cluster) to be automatically replaced if they failed to provision in the first place. Without this logic, the user would need to look at the HCP UI to determine their cluster/HVN/peering is in a `FAILED` state, and delete/recreate manually using Terraform (or the UI and remove …

Set resource id before polling operation and re-create failed deployments

---

README.md

Ran into an issue where I needed to upgrade to v0.14 to use my handcrafted organic locally built provider, so I thought I'd add this caveat to the README.

add README example for using local binary

---

docs/resources/aws_transit_gateway_attachment.md
examples/resources/hcp_aws_transit_gateway_attachment/import.sh
internal/provider/resource_aws_transit_gateway_attachment.go
templates/resources/aws_transit_gateway_attachment.md.tmpl

Adds import functionality, where the import id is `{hvn_id}:{transit_gateway_attachment_id}`
Most of the functionality matches what is already done with network peering.
One note: because `resource_share_arn` is not available in our responses, it cannot be populated into Terraform state from an import. This is a known case that can be handled with an `ignore_changes` block (I've included this in the documentation here), but the preferred solution would be to include this value in the response, if that is an option here.

HCPE-909 - Add TGW attachment imports

---

docs/data-sources/consul_versions.md
examples/data-sources/hcp_consul_versions/data-source.tf
internal/clients/consul_cluster.go
internal/consul/version.go
internal/consul/version_test.go
internal/provider/data_source_consul_versions.go
internal/provider/provider.go
internal/provider/resource_consul_cluster.go

Based off the [`hcs_consul_versions` data source](https://registry.terraform.io/providers/hashicorp/hcs/latest/docs/data-sources/consul_versions), we can allows users to explicitly set their Consul cluster version to the latest recommended Consul version that HCP supports. This means that any time the recommended HCP Consul version changes, someone utilizing the `recommended` field of the `consul_versions` data source will be prompted to upgrade their cluster the next time they run `terraform plan`:
```
❯ terraform plan
hcp_hvn.example_hvn: Refreshing state... 
hcp_consul_cluster.example_consul_cluster: Refreshing state... 
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the …
```

HCS-1760: Add Consul versions data source

---

docs/data-sources/consul_cluster.md
docs/guides/consul-federation.md
docs/index.md
docs/resources/consul_cluster.md
examples/guides/consul_cluster_federation/_config.tf
examples/guides/consul_cluster_federation/main.tf
examples/guides/consul_cluster_federation/variables.tf
examples/provider/provider.tf
examples/resources/hcp_consul_cluster/federation.tf
go.mod
go.sum
internal/clients/consul_cluster.go
internal/clients/consul_snapshot.go
internal/clients/response.go
internal/provider/data_source_consul_cluster.go
internal/provider/resource_consul_cluster.go
internal/provider/resource_consul_cluster_root_token.go
templates/guides/consul-federation.md.tmpl

Adds federation support for HCP Consul.

HCS-1716: Add HCP Consul federation support

---

docs/data-sources/aws_transit_gateway_attachment.md
docs/resources/aws_transit_gateway_attachment.md
templates/data-sources/aws_transit_gateway_attachment.md.tmpl
templates/resources/aws_transit_gateway_attachment.md.tmpl

This adds a banner to the docs for transit gateway attachment resources, since they are still in private beta and behind a feature flag. When the next version of the provider is published, these pages will be visible to all users, so this banner will help prevent confusion.

Add beta banner to docs for TGW attachment resources

---

internal/provider/provider_test.go
internal/provider/resource_hvn_test.go

Add basic acceptance tests for creating, updating, and destroying an HVN.
Acceptance tests need to be run locally, which requires creating a service principal, and setting the env variables:
- `export HCP_CLIENT_ID=...`
- `export HCP_CLIENT_SECRET=...`
- `make acctest`

HCPE-998 - Add acceptance tests for HVN resource

---

internal/provider/resource_consul_cluster_test.go
internal/provider/resource_hvn_test.go

Add a simple Consul acceptance test, which mainly just verifies that all of the fields get set appropriately on create.
Note for anyone interested in testing this locally: this test was taking >10 mins for me to run.

HCPE-1032 - Add basic consul acceptance test

---

go.mod
go.sum
internal/clients/consul_cluster.go
internal/clients/consul_snapshot.go

This PR bumps the dependency [hcp-sdk-go](https://github.com/hashicorp/hcp-sdk-go) to v0.5.0, capturing this [list of changes](https://github.com/hashicorp/hcp-sdk-go/compare/v0.2.0...v0.5.0). Highlights include - complete API errors can now be surfaced, a new version of the Consul API, and the addition of the Vault API!

Bump hcp-go-sdk to v0.5.0

---

internal/provider/provider.go
internal/provider/resource_vault_cluster.go
internal/provider/resource_vault_cluster_admin_token.go

This PR adds the schema for the new Vault cluster resource. It takes some inspiration from the Consul cluster resource.
Sample HCL:
```
resource "hcp_vault_cluster" "example" {
cluster_id = "testing"
hvn_id = "test-hvn"
public_endpoint = true
initial_vault_version = "1.7.0"
}
```
Sample `terraform plan` output:
```
+ resource "hcp_vault_cluster" "example" {
+ cloud_provider               = (known after apply)
+ cluster_id                   = "testing"
+ created_at                   = (known after apply)
+ hvn_id                       = "test-hvn"
+ id                           = (known after apply)
+ namespace                    = "admin"
+ organization_id              = (known after apply)
+ project_id                   = (known after apply)
+ region                       = (known after …
```

HCPE-1034: vault resource scaffolding

---

contributing/README.md
contributing/pull-request-lifecycle.md

Added docs to describe the PR lifecycle, meant primarily for new contributors.
```
...
```

HCPE-996 - Add pull request lifecycle docs

---

.github/workflows/terraform_provider.yml
GNUmakefile
scripts/gofmtcheck.sh

Added GitHub checks (and `make` targets) for:
- `depscheck` - Run `go mod tidy` and make sure there are no differences
- `fmtcheck` - Make sure `gofmt` has been run on all Go files
- `gencheck` - Run `go generate` and make sure there are no differences
I chose these checks to start since they don't require any additional tools to run. Also note that there is no cache being used here, so that might be something we want to look at if these checks start taking a long time to run.
For reference:
- AWS provider [gofmtcheck.sh](https://github.com/hashicorp/terraform-provider-aws/blob/main/scripts/gofmtcheck.sh), [makefile](https://github.com/hashicorp/terraform-provider-aws/blob/main/GNUmakefile), and [CI checks](https://github.com/hashicorp/terraform-provider-aws/tree/main/.github/workflows)
- …

HCPE-926 - Add github checks for depscheck, fmtcheck, and gencheck

---

docs/resources/vault_cluster.md
internal/consul/version.go
internal/consul/version_test.go
internal/input/input.go
internal/input/input_test.go
internal/provider/link.go
internal/provider/resource_consul_cluster.go
internal/provider/resource_vault_cluster.go
internal/provider/resource_vault_cluster_test.go

This PR adds the Vault cluster resource.
Sample HCL:
```
resource "hcp_hvn" "example" {
hvn_id          = "test-hvn"
cloud_provider  = "aws"
region          = "us-west-2"
}
resource "hcp_vault_cluster" "example" {
cluster_id         = "test-vault-cluster"
hvn_id             = hcp_hvn.example.hvn_id
min_vault_version  = "v1.7.0"
}
```
Sample `terraform plan` output:
```
+ resource "hcp_vault_cluster" "example" {
+ cloud_provider               = (known after apply)
+ cluster_id                   = "test-vault-cluster"
+ created_at                   = (known after apply)
+ hvn_id                       = "test-hvn"
+ id                           = (known after apply)
+ namespace                    = "admin"
+ organization_id              = (known after apply)
+ project_id                   = …
```

HCPE-980: Vault cluster resource

---

README.md
docs/data-sources/aws_network_peering.md
docs/data-sources/aws_transit_gateway_attachment.md
docs/guides/peering.md
docs/guides/quick-start.md
docs/index.md
docs/resources/aws_network_peering.md
docs/resources/aws_transit_gateway_attachment.md
examples/data-sources/hcp_aws_network_peering/variables.tf
examples/guides/peering/main.tf
examples/guides/peering/variables.tf
examples/provider/provider.tf
internal/clients/peering.go
internal/clients/tgw.go
internal/provider/data_source_aws_network_peering.go
internal/provider/data_source_aws_transit_gateway_attachment.go
internal/provider/link.go
internal/provider/resource_aws_network_peering.go
internal/provider/resource_aws_transit_gateway_attachment.go
templates/guides/peering.md.tmpl
templates/guides/quick-start.md.tmpl

These changes will probably be easiest to review one commit at a time. The updates largely come from items we ran into while working on the TGW resource, but did not yet backport to the other resources:
- **fix:** Ensure context is being passed for all HCP API calls - https://github.com/hashicorp/terraform-provider-hcp/commit/27be4da53d37f8199e87442c8ad2df0ad739c49f
- **improvement:** Update comments, docs, and messages to use correct capitalization for network peering - https://github.com/hashicorp/terraform-provider-hcp/commit/e8015376a8d2f7215bb631a54150222b909769e9
- **improvement:** Log import ID used when an import fails due to parsing - https://github.com/hashicorp/terraform-provider-hcp/commit/8204243661125969be973ea0f742cef229284465
- **improvement:** Add comment to clarify that …

Update resources to be in line with current patterns

---

internal/provider/data_source_consul_agent_helm_config.go

This PR updates the logic for generating the `k8sAuthMethodHost` within the `hcp_consul_agent_helm_config` data source.
As it stands now we always prepend an `https://` protocol to the `kubernetes_endpoint` string provided. This updated logic will strip a leading `https://` from the `kubernetes_endpoint` string and will leverage the existing logic to prepend the protocol again as needed.  This will allow for handling of both cases of this string having a leading `https://` and not.
With the following `main.tf`
```
<PROVIDER set-up>
data "hcp_consul_agent_helm_config" "test" {
cluster_id = "consul-cluster"
kubernetes_endpoint = "https://catter.com"
}
```
resulted with the following in `terraform.state` file:
```
...
k8sAuthMethodHost: https://catter.com:443
...
```
The above output is seen …

[HCS-1831] Remove extraneous protocol from fqdn string if present

---

docs/data-sources/consul_cluster.md
docs/resources/consul_cluster.md
go.mod
internal/clients/client.go
internal/clients/consul_cluster.go
internal/clients/consul_snapshot.go
internal/consul/version.go
internal/consul/version_test.go
internal/provider/data_source_consul_cluster.go
internal/provider/data_source_consul_versions.go
internal/provider/resource_consul_cluster.go
internal/provider/resource_consul_snapshot.go
internal/provider/validators.go
internal/provider/validators_test.go

- Adds a size attribute to the consul cluster properties. This can be provided during creation to specify t-shirt size of each server.
- Updates the hcp-go-sdk version.
- Cleans up some tier related validation in favor of leveraging sdk provided validation.

HCS-1805: Add consul cluster vm size

---

README.md
docs/data-sources/vault_cluster.md
docs/guides/vault-admin-token.md
docs/index.md
docs/resources/vault_cluster.md
examples/data-sources/hcp_vault_cluster/data-source.tf
examples/guides/vault_cluster_admin_token/main.tf
examples/provider/provider.tf
examples/resources/hcp_vault_cluster/import.sh
examples/resources/hcp_vault_cluster/resource.tf
internal/provider/data_source_vault_cluster.go
internal/provider/provider.go
internal/provider/resource_vault_cluster.go
internal/provider/resource_vault_cluster_test.go
templates/guides/vault-admin-token.md.tmpl

This PR adds the Vault cluster data source, import, and updates documentation with examples and a new guide! 📓 ✨ 
**Data Source:**
```
data "hcp_vault_cluster" "example" {
cluster_id = "vault-cluster"
}
```
**Import:**
```
terraform import hcp_vault_cluster.example vault-cluster
```
```
$ make testacc TESTARGS='-run=TestAccVaultCluster'
--- PASS: TestAccVaultCluster (702.59s)
PASS
```

HCPE-978: Vault cluster data source, import, and docs

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

We got Vault resources and Consul cluster VM sizes incoming! 🚀

Update changelog for 0.4.0 release

---

docs/data-sources/consul_cluster.md
docs/resources/consul_cluster.md
internal/provider/data_source_consul_cluster.go
internal/provider/resource_consul_cluster.go

- `size` is an optional field on Consul cluster create. If customers have not specified it in the config, without the "computed=true" option it forces recreation of the cluster.
- Also updated the size desc to include the link with more details.

HCS-1805-hotfix: Set "computed=true" option for the vm size

---

docs/data-sources/aws_network_peering.md
docs/data-sources/aws_transit_gateway_attachment.md
docs/data-sources/hvn.md
docs/resources/aws_network_peering.md
docs/resources/aws_transit_gateway_attachment.md
docs/resources/hvn.md
internal/provider/data_source_aws_network_peering.go
internal/provider/data_source_aws_transit_gateway_attachment.go
internal/provider/data_source_hvn.go
internal/provider/resource_aws_network_peering.go
internal/provider/resource_aws_transit_gateway_attachment.go
internal/provider/resource_hvn.go
internal/provider/resource_hvn_test.go

Added `self_link` attribute to hvn, peering and tgw attachment resources and datasources.

added self_link to hvn, peering and tgw attachment

---

.gitignore
internal/provider/resource_consul_snapshot_test.go

Adds acceptance tests for Consul cluster snapshots
```
$ make testacc TESTARGS='-run=TestAccConsulSnapshot'
TF_ACC=1 go test ./internal/... -v -run=TestAccConsulSnapshot -timeout 120m
PASS
PASS
=== RUN   TestAccConsulSnapshot
--- PASS: TestAccConsulSnapshot (567.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	572.920s
```

HCPE-1032: Add Consul cluster snapshot acceptance tests

---

CHANGELOG.md
docs/index.md
templates/index.md.tmpl

This PR removes the v0.4.0 warning from the registry index page. The warning will stay in the changelog forever.
In its place, I've added a warning about the upcoming breaking changes in our networking resources. 
I'll be releasing publishing these changes to the registry as a patch, v0.6.1. Since there are no feature changes in this tiny release, I did not update the version used in our examples.

remove v0.4.0 warning and replace with upcoming migration in index page

---

internal/provider/resource_hvn_route.go

Treat `NotFound` as success when deleting HVN routes

added handling 404 when deleting hvn route

---

docs/resources/hvn_route.md
internal/provider/resource_hvn_route.go

Added timeout for HVN route delete, otherwise on destroy it was failing with error like:
```
Error: unable to delete HVN route (tgw-route-1): context canceled waiting for delete HVN route operation (72667030-7343-4592-9a88-93d9f7cf0473) to complete
```

added dedicated timeout for hvn route delete

---

internal/provider/resource_consul_cluster_test.go

Because the root token has a no-op for reading the resource, we only
create the token to ensure that it does not error upon creation.
```
$ make testacc TESTARGS='-run=TestAccConsulCluster'
TF_ACC=1 go test ./internal/... -v -run=TestAccConsulCluster -timeout 120m
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/consul	0.190s [no tests to run]
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/input	0.150s [no tests to run]
=== RUN   TestAccConsulCluster
--- PASS: TestAccConsulCluster (585.82s)
PASS
ok …
```

Test creation on Consul cluster root token

---

.github/CODEOWNERS

Updates the CODEOWNERS file to include backend team reviewers on their relevant files. I've tested the file syntax out by messing with `.gitignore` locally, so I'm fairly confident they'll target the right files. But fine-tuning may be needed. 🤓

add team ownership to CODEOWNERS

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

In preparation for release of 0.8.0!
```
$ make testacc
--- PASS: TestAccHvnPeering (224.95s)
--- PASS: TestAccTGWAttachment (514.70s)
--- PASS: TestAccConsulCluster (543.60s)
--- PASS: TestAccConsulSnapshot (611.61s)
--- PASS: TestAccHvnRoute (220.75s)
--- PASS: TestAccHvn (74.41s)
--- PASS: TestAccVaultCluster (653.02s)
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	2843.669s
```

Update changelog for 0.8.0

---

contributing/writing-tests.md
docs/resources/vault_cluster.md
internal/clients/vault_cluster.go
internal/provider/data_source_consul_cluster.go
internal/provider/data_source_vault_cluster.go
internal/provider/resource_consul_cluster.go
internal/provider/resource_vault_cluster.go
internal/provider/resource_vault_cluster_test.go

Jumping off @bplotnick's contribution https://github.com/hashicorp/terraform-provider-hcp/pull/118, I've implemented the Vault cluster resource Update function to enable updating `public_endpoint` without forcing the recreation of the cluster.
```
$ make testacc TESTARGS='-run=TestAccVaultCluster'
--- PASS: TestAccVaultCluster (639.36s)
```

implement Vault update (public_endpoint only)

---

docs/guides/consul-root-token.md
templates/guides/consul-root-token.md.tmpl

This adds some additional guidance around the Consul root token resource and how it can be used with the Consul provider.
https://github.com/hashicorp/terraform-provider-hcp/issues/131

add note about configuring Consul provider

---

go.mod
internal/provider/resource_consul_cluster.go

If an update fails subsequent terraform runs consider the state correct. This is because the current cluster version is not validated against the min_consul_version.
Added  min_consul_version to read and set it to the consul_version. We can suppress the diff when the cluster version is greater than or equal to the what is set in the terraform by the user.
- ~~[ ] Are there any feature flags that are required to use this functionality?~~
- ~~[ ] Have you added an acceptance test for the functionality being added?~~
-  Ran manual tests extensively in cases where user setup would cause update errors. Validated that it works correctly.

Fix terraform updates for min_consul_version

---

README.md
design/networking-abstractions.md
docs/index.md
internal/provider/resource_aws_network_peering.go
internal/provider/resource_aws_transit_gateway_attachment.go
templates/index.md.tmpl

This PR sets up a new directory called `design`, where we save records of architectural designs made as we implement the HCP provider. The first such design doc is on how we decided to handle abstractions over our networking resources.
Also includes a bonus wording fix in the overview banner.

HCPE-1281: add design doc on networking resources

---

go.mod
internal/provider/resource_consul_cluster.go

If an update fails subsequent terraform runs consider the state correct. This is because the current cluster version is not validated against the min_consul_version.
Added  min_consul_version to read and set it to the consul_version. We can suppress the diff when the cluster version is greater than or equal to the what is set in the terraform by the user.
- ~~[ ] Are there any feature flags that are required to use this functionality?~~
- ~~[ ] Have you added an acceptance test for the functionality being added?~~
-  Ran manual tests extensively in cases where user setup would cause update errors. Validated that it works correctly.

Fix terraform updates for min_consul_version after revert

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

In preparation for today's release of 0.10.0. 🎉 
```
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	4025.109s
```

Update changelog for 0.10.0 release

---

docs/resources/consul_cluster.md
internal/provider/resource_consul_cluster.go

```release-note
```
```
...
```

docs: updated the language for the hcp_consul_cluster resource

---

docs/resources/vault_cluster.md
go.mod
go.sum
internal/provider/resource_vault_cluster.go
internal/provider/validators_test.go

This adds support for the newly launched `starter_small` HCP Vault cluster tier. The HCP SDK was bumped to support this change.
```release-note
* resource/hcp_vault_cluster: add `starter_small` cluster tier
```
```
$ make testacc TESTARGS='-run=TestAccVaultCluster'
TF_ACC=1 go test ./internal/... -v -run=TestAccVaultCluster -timeout 120m
PASS
PASS
ok …
```

Add starter_small HCP Vault cluster tier

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Updates the CHANGELOG and example provider version in preparation for releasing v0.12.0.
```
$ make testacc
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	3257.108s
```

Prep 0.12.0 release

---

internal/provider/data_source_packer_image_iteration.go
internal/provider/data_source_packer_image_iteration_test.go

This change adds a few new helper functions for deleting resources on the HCP Packer registry under tests.
```shellsession
$ make testacc TESTARGS='-count=1 -run=TestAcc_dataSourcePacker'
TF_ACC=1 go test ./internal/... -v -count=1
-run=TestAcc_dataSourcePacker -timeout 120m
?       github.com/hashicorp/terraform-provider-hcp/internal/clients
[no test files]
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/consul
0.172s [no tests to run]
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/input
0.127s [no tests to run]
--- PASS: TestAcc_dataSourcePacker (6.47s)
PASS …
```

Add CheckDestroy step for Packer Data Source Test

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Prep for v0.13.0 release, featuring HCP Packer's first data source in private beta!
⚠️ Ran into some environment issues while running these, so VaultCluster and TGWAttachment tests were verified separately.
```
$ make testacc
--- PASS: TestAcc_dataSourcePacker (8.93s)
--- PASS: TestAccHvnPeering (212.71s)
--- PASS: TestAccConsulCluster (503.15s)
--- PASS: TestAccConsulSnapshot (516.13s)
--- PASS: TestAccHvnPeeringConnection (102.53s)
--- PASS: TestAccHvnRoute (201.92s)
--- PASS: TestAccHvn (73.03s)
--- PASS: TestAccVaultCluster (702.39s)
--- PASS: TestAccTGWAttachment (482.69s)
```

Prep v0.13.0

---

internal/clients/consul_cluster.go
internal/provider/resource_consul_cluster.go
internal/provider/resource_consul_cluster_test.go

- remove `ForceNew` on consul cluster size field - we want to update the resource instead of destroy and recreate
- modify `resourceConsulClusterUpdate` to handle size change 
- note: the logic to validate size upgrade paths is already in consul service so it is not needed here
- tested size upgrade using terraform with consul cluster in integration (currently behind launchdarkly flag)
- HCP TF provider should call the consul-service update cluster API on a change in the value for size , instead of re-creating the cluster. 
- The PR should be approved from a consul-service engineer and a TCE team engineer
- PR will not be merged until monitoring is added

HCS-2061: Add size upgrade field for consul cluster update

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Prep for v0.14.0 release, featuring the ability to update Consul cluster size! 🎆 
TGW and HVN Peering Connections were tested against a separate environment.
```
--- PASS: TestAccConsulCluster (581.00s)
--- PASS: TestAccConsulSnapshot (553.94s)
--- PASS: TestAcc_dataSourcePacker (13.10s)
--- PASS: TestAccHvn (75.74s)
--- PASS: TestAccHvnPeering (218.14s)
--- PASS: TestAccHvnRoute (209.62s)
--- PASS: TestAccVaultCluster (690.41s)
--- PASS: TestAccTGWAttachment (476.26s)
--- PASS: TestAccHvnPeeringConnection (119.57s)
```

Prep 0.14.0

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Prep for release of v0.15.0.
```
$ make testacc
PASS	github.com/hashicorp/terraform-provider-hcp/internal/provider	3219.899s
```

Prep v0.15.0

---

docs/resources/consul_cluster.md
internal/provider/resource_consul_cluster.go

Updated the resource `hcp_consul_cluster` `size` field description to specify support for size upgrade.

Update docs about HCP Consul size upgrade support

---

go.mod
go.sum
internal/clients/consul_cluster.go

Setting PlatformType explicitly to HCP for the ListVersions call. 
```release-note
* NONE
```
- [n/a] Are there any feature flags that are required to use this functionality?
- [n/a] Have you added an acceptance test for the functionality being added?
```
$make testacc TESTARGS='-run=TestAccConsulCluster'
TF_ACC=1 go test ./internal/... -v -run=TestAccConsulCluster -timeout 120m
PASS …
```

Set PlatformType to HCP explicitly

---

docs/data-sources/packer_image.md
internal/provider/data_source_packer_image.go
internal/provider/data_source_packer_image_iteration_test.go
internal/provider/data_source_packer_image_test.go

Adds build labels to the schema and sets them so users can access them. 
```release-note
* {hcp_packer_image }: {Add build labels to the hcp_packer_image data source} [GH-217]
```
```
make testacc TESTARGS="-run TestAcc_dataSourcePackerImage"
TF_ACC=1 go test ./internal/... -v -run TestAcc_dataSourcePackerImage -timeout 120m
PASS
PASS
ok …
```

add labels to the returned image data

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Preps the release of 0.20.0, which includes some dependency bumps and adds `labels` to the packer image datasource.
```
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	4344.272s
```

Prep 0.20.0 release

---

internal/clients/vault_cluster.go
internal/provider/resource_vault_cluster.go
internal/provider/resource_vault_cluster_test.go

Implement Vault cluster scaling. When the `tier` is changed, invoke a scaling operation to scale the cluster to the new tier.
```release-note
* Vault cluster: implement cluster tier scaling [GH-228]
```
```
$ make testacc TESTARGS='-run= TestAccVaultCluster'
... <7014 lines of output>
--- PASS: TestAccVaultCluster (1498.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	1499.340s
```

Implement Vault cluster scaling

---

internal/clients/packer.go
internal/provider/data_source_packer_image_iteration_test.go
internal/provider/data_source_packer_image_test.go
internal/provider/data_source_packer_iteration_test.go

The upstream Packer cloud service has been updated to return actionable errors for the majority of its endpoints. This change updates the client functions to return only the error message, stripped of any HTTP methods or status codes, from the API.
Closes #224 
```release-note
* datasource/packer: Improve error messages for requests made to HCP Packer. [GH-229](https://github.com/hashicorp/terraform-provider-hcp/pull/229)
```
```
$ make testacc TESTARGS='-run=TestAcc_dataSourcePacker'
...
```
<details>
<summary> Updated Error Messaging </summary>
```
~>  terraform apply
╷
│ Error: This HCP Packer registry was deactivated by the administrator. To …
```

Update the error messaging for the Packer service datasources

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Prep for the release of v0.21.0, which includes update-able tiers on Vault clusters and beautified error messaging on the Packer datasource! ✨ 
**Note:** Some tests failed on initial run due to transient environmental issues, so I re-ran them separately.
```
--- PASS: TestProvider (0.00s)
--- PASS: TestAccHvnPeering (574.74s)
--- PASS: TestAccConsulCluster (1240.86s)
--- PASS: TestAccConsulSnapshot (737.67s)
--- PASS: TestAccHvnPeeringConnection (304.21s)
--- PASS: TestAccHvnRoute (691.75s)
--- PASS: TestAccHvn (146.21s)
--- PASS: TestAccVaultCluster (2496.24s)
--- PASS: TestAcc_dataSourcePackerIteration (7.01s)
--- PASS: TestAcc_dataSourcePackerImage (7.48s)
--- PASS: TestAcc_dataSourcePacker (8.97s)
--- PASS: TestAccTGWAttachment (514.86s) …
```

Prep v0.21.0

---

internal/provider/resource_vault_cluster.go

When changing vault cluster tiers, do not `ForceNew`.
```release-note
* Vault cluster: fix to tier scaling [GH-233]
```
```
...
```

Vault cluster scaling

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf
templates/index.md.tmpl

⚠️ `v0.21.0` included an escaped defect, in which Terraform will incorrectly recommend a rebuild of a Vault cluster if the tier is changed, which could result in data loss. For this reason, that release is no longer available for use. Please upgrade to the patch `v0.21.1` once released.
Prep release of 0.21.1, which includes a hot fix to prevent Vault cluster tier updates from re-creating the cluster.
```
--- PASS: TestProvider (0.00s)
--- PASS: TestAccHvnPeering (574.74s)
--- PASS: TestAccConsulCluster (1240.86s)
--- PASS: TestAccConsulSnapshot (737.67s)
--- PASS: TestAccHvnPeeringConnection (304.21s)
--- PASS: TestAccHvnRoute (691.75s)
--- PASS: TestAccHvn (146.21s)
--- PASS: TestAccVaultCluster (2496.24s)
--- PASS: …
```

Prep v0.21.1

---

go.mod
go.sum
internal/clients/client.go
internal/clients/vault_cluster.go
internal/provider/data_source_packer_image.go
internal/provider/data_source_packer_image_iteration.go
internal/provider/data_source_packer_image_iteration_test.go
internal/provider/data_source_packer_image_test.go
internal/provider/data_source_packer_iteration.go
internal/provider/data_source_packer_iteration_test.go
internal/provider/resource_vault_cluster.go
internal/provider/validators.go
internal/provider/validators_test.go

This adds a check for revoked iterations. For HCP Packer GA, revoking iterations will be possible and if an iteration is revoked it must never be used and the `terraform plan|apply` should fail. 
Since I updated the hcp-sdk-go version, I had to make some changes to vault's import and tests. Changes were checked and validated with @kkredit 
```release-note
* datasource/hcp_packer_image: Add check for revoked iterations [GH-240]
* datasource/hcp_packer_iteration: Add check for revoked iterations [GH-240]
* datasource/hcp_packer_image_iteration: Add check for revoked iterations [GH-240]
```
```
$ make testacc TESTARGS='-run=TestAcc_dataSourcePacker'
==> …
```

Add check for revoked iterations to HCP Packer datasources

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Preps release of v0.22.0, which includes a Consul doc fix and a Packer datasource improvement.
```
--- PASS: TestAccHvnPeering (631.62s)
--- PASS: TestAccTGWAttachment (528.28s)
--- PASS: TestAccConsulCluster (1403.59s)
--- PASS: TestAccConsulSnapshot (830.49s)
--- PASS: TestAccHvnPeeringConnection (262.14s)
--- PASS: TestAccHvnRoute (581.28s)
--- PASS: TestAccHvn (151.58s)
--- PASS: TestAccVaultCluster (2093.66s)
```

Prep v0.22.0

---

docs/resources/hvn.md
internal/provider/resource_consul_cluster.go
internal/provider/resource_hvn.go
internal/provider/resource_hvn_test.go

This PR adds support for Consul on Azure with updates to the `hcp_hvn` and `hcp_consul_cluster` resources. **This feature is available for internal users only.**
```release-note
* resource/consul_cluster: adds Azure on Consul (internal only)  [GH-247]
```
```
provider "hcp" {}
resource "hcp_hvn" "hvn" {
hvn_id         = "hvn-test"
cloud_provider = "azure"
region         = "useast"
cidr_block     = "172.25.16.0/20"
}
resource "hcp_consul_cluster" "example" {
cluster_id = "azure-consul-cluster"
hvn_id     = hcp_hvn.hvn.hvn_id
tier       = "standard"
size       = "small"
}
```
TODO.
```
...
```

TCE-1769: Azure networking resources (internal only)

---

go.mod
go.sum

Combines the last few dependency bot PRs into one big dependency bump.
```release-note
* provider: bump multiple dependencies (go-openapi/runtime, go-openapi/strfmt, google.golang.org/grpc, hashicorp/go-version, terraform-plugin-sdk/v2)  [GH-nnnn]
```
```
$ make testacc
--- PASS: TestAccConsulCluster (1634.46s)
--- PASS: TestAccConsulSnapshot (852.26s)
--- PASS: TestAcc_dataSourcePacker (34.58s)
--- PASS: TestAcc_dataSourcePacker_revokedIteration (12.34s)
--- PASS: TestAcc_dataSourcePackerImage (21.23s)
--- PASS: TestAcc_dataSourcePackerIteration (20.63s)
--- PASS: TestAcc_dataSourcePackerIteration_revokedIteration (9.82s)
--- PASS: TestAccHvnPeering …
```

multiple dependency bump

---

internal/provider/data_source_packer_image.go
internal/provider/data_source_packer_image_iteration.go
internal/provider/data_source_packer_image_iteration_test.go
internal/provider/data_source_packer_iteration.go
internal/provider/data_source_packer_iteration_test.go

The `hcp_packer_x` datasources were checking if an iteration had a `revoke_at` to tell if it's revoked or not. This was wrong because a revoke_at set to the future means that revocation is scheduled and the iteration is currently valid. 
This PR fixes this behaviour and only fails for `revoked_at <= now`
```release-note
* datasource/hcp_packer_image: Fix check for revoked iterations to consider scheduled revocation valid [GH-262]
* datasource/hcp_packer_iteration: Add check for revoked iterations to consider scheduled revocation valid [GH-262]
* datasource/hcp_packer_image_iteration: Add check for revoked iterations to consider scheduled revocation valid [GH-262]
```
Output from …

Do not fail packer datasources for iteration with revoke_at set to the future

---

docs/data-sources/aws_network_peering.md
docs/guides/peering.md
examples/data-sources/hcp_aws_network_peering/data-source.tf
examples/guides/peering/main.tf
internal/provider/data_source_aws_network_peering.go

This PR adds the `wait_for_active_state` to the AWS peering datasource. This flag can be used in conjunction with a peering resource to ensure there is no race condition between HVN route and peering connection creation.
The issue that arises is that the peering resource initially returns in a `pending` state, because it must be accepted on the AWS side (by the `aws_vpc_peering_connection_accepter`). Once it is accepted, it becomes `active`. The HVN route resource requires an active peering connection to successfully create, but since the peering returns in a `pending` state, a race occurs between creation of the HVN route and peering acceptance. The HVN route can get stuck in a `pending` state.
The `wait_for_active_state` flag on the peering datasource solves this issue. Since the …

Add wait_for_active_state to AWS peering datasource

---

CHANGELOG.md
docs/data-sources/azure_peering_connection.md
docs/index.md
docs/resources/azure_peering_connection.md
examples/provider/provider.tf
internal/provider/resource_aws_transit_gateway_attachment_test.go
templates/data-sources/azure_peering_connection.md.tmpl
templates/index.md.tmpl
templates/resources/azure_peering_connection.md.tmpl

Preps the release of v0.23.0.
As a bonus, fixes the TGW acceptance test flakiness.
```
$ make testacc
--- PASS: TestAcc_dataSourcePacker (8.67s)
--- PASS: TestAcc_dataSourcePacker_revokedIteration (8.01s)
--- PASS: TestAcc_dataSourcePacker_iterationScheduledToBeRevoked (7.31s)
--- PASS: TestAcc_dataSourcePackerImage (7.65s)
--- PASS: TestAcc_dataSourcePackerIteration (7.00s)
--- PASS: TestAcc_dataSourcePackerIteration_revokedIteration (7.50s)
--- PASS: TestAcc_dataSourcePackerIteration_iterationScheduledToBeRevoked (7.28s)
--- PASS: TestAccAwsPeering (701.04s)
--- PASS: TestAccHvnPeeringConnection (298.53s)
--- PASS: TestAccHvnRoute (662.17s)
--- PASS: TestAccHvnOnly (139.74s)
--- PASS: TestAccTGWAttachment (767.44s)
--- PASS: TestAccConsulCluster …
```

Prep 0.23.0

---

internal/provider/data_source_packer_image.go
internal/provider/data_source_packer_image_iteration.go
internal/provider/data_source_packer_image_iteration_test.go
internal/provider/data_source_packer_image_test.go
internal/provider/data_source_packer_iteration.go
internal/provider/data_source_packer_iteration_test.go

This removes the hcp packer iteration revocation check.
```release-note
* datasource/hcp_packer_image: Remove check for revoked iterations [GH-264]
* datasource/hcp_packer_iteration: Remove check for revoked iterations [GH-264]
* datasource/hcp_packer_image_iteration: Remove check for revoked iterations [GH-264]
```
```
TF_ACC=1 go test ./internal/... -v -run=TestAcc_dataSourcePacker -timeout 120m
?       github.com/hashicorp/terraform-provider-hcp/internal/clients    [no test files]
PASS …
```

Remove revocation check

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf
internal/provider/resource_hvn_route_test.go

Preps patch 0.23.1, with a Packer fix for revoked iterations.
```
$ make testacc
--- PASS: TestAcc_dataSourcePacker (9.47s)
--- PASS: TestAcc_dataSourcePackerImage (7.78s)
--- PASS: TestAcc_dataSourcePackerImage_revokedIteration (11.71s)
--- PASS: TestAcc_dataSourcePackerIteration (7.17s)
--- PASS: TestAccAwsPeering (723.25s)
--- PASS: TestAccTGWAttachment (728.34s)
--- PASS: TestAccHvnOnly (152.64s)
--- PASS: TestAccHvnRoute (715.49s)
--- PASS: TestAccConsulCluster (1342.73s)
--- PASS: TestAccConsulSnapshot (884.67s)
--- PASS: TestAccHvnPeeringConnection (297.26s)
--- PASS: TestAccVaultCluster (2306.89s)
```

Prep 0.23.1

---

internal/provider/resource_consul_cluster.go
internal/provider/resource_consul_cluster_test.go

This commit fixes an issue where we would always suppress the
min_consul_version on create, because a previous value for the cluster
did not exist to compare against.
```release-note
* hcp_consul_cluster: Fix min_consul_version on creation not taking affect [GH-252]
```
```
$ make testacc TESTARGS='-run=TestAccConsulCluster'
TF_ACC=1 go test ./internal/... -v -run=TestAccConsulCluster -timeout 120m
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/consul	0.159s [no …
```

HCS-2849: Do not suppress min_consul_version on creation

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Preps the release of 0.24.0, which includes plus-tier Consul cluster performance replication as well as a Consul cluster min_version fix!
```
$ make testacc
--- PASS: TestAcc_dataSourcePacker (8.63s)
--- PASS: TestAcc_dataSourcePackerImage (8.27s)
--- PASS: TestAcc_dataSourcePackerImage_revokedIteration (11.92s)
--- PASS: TestAcc_dataSourcePackerIteration (7.44s)
--- PASS: TestAccHvnOnly (116.67s)
--- PASS: TestAccAwsPeering (722.72s)
--- PASS: TestAccTGWAttachment (1094.38s)
--- PASS: TestAccHvnPeeringConnection (283.36s)
--- PASS: TestAccHvnRoute (768.12s)
--- PASS: TestAccConsulCluster (1530.54s)
--- PASS: TestAccConsulSnapshot (963.21s)
```

Prep 0.24.0

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Preps the release of 0.24.1, which includes removing the beta notes from Packer datasources in docs.
This is just a documentation update.
```
...
```

Prep 0.24.1

---

docs/data-sources/vault_cluster.md
docs/guides/vault-performance-replication.md
docs/guides/vault-scaling.md
docs/resources/vault_cluster.md
examples/guides/vault_perf_replication/replication.tf
go.mod
go.sum
internal/clients/vault_cluster.go
internal/provider/data_source_vault_cluster.go
internal/provider/resource_vault_cluster.go
internal/provider/resource_vault_cluster_test.go
internal/provider/validators.go
internal/provider/validators_test.go
templates/guides/vault-performance-replication.md.tmpl
templates/guides/vault-scaling.md.tmpl

Vault: enable configuring the `paths_filter` on performance replicated secondaries and enable scaling of Plus-tier clusters.
```release-note
* Vault: enable paths_filter and scaling in Plus-tier [GH-281]
```
```
$ make testacc TESTARGS='-run=TestAccPerformanceReplication_Validations'
TF_ACC=1 go test ./internal/... -v -run=TestAccPerformanceReplication_Validations -timeout 120m
?       github.com/hashicorp/terraform-provider-hcp/internal/clients    [no test files]
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/consul     (cached) [no tests to …
```

Vault: enable paths_filter and scaling for Plus-tier

---

internal/provider/provider.go

Consul-related operations were being blocked on a Vault-related outage. This change makes it so that the operation will continue if there's an outage, and we'll show the warning notifying users there may be issues.
```release-note
* all: Don't block Terraform operations on HCP system outages [GH-290]
```
```
...
```

only warn on all platform statuses

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

This release includes a fix that allows the provider to continue working during an outage.
Note: In the interest of getting a fix out quickly, only the Consul tests were run.
```
$ make testacc TESTARGS='-run=TestAccConsulCluster'
--- PASS: TestAccConsulCluster (1480.85s)
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	1485.755s
```

Prep 0.26.0

---

docs/resources/azure_peering_connection.md
examples/resources/hcp_azure_peering_connection/resource.tf

Fixes Azure peering documentation example.
```release-note
* docs: fix peer_vnet_region in azure_peering example [GH-nnnn]
```

fix peer_vnet_region in azure_peering example

---

.github/CODEOWNERS
internal/provider/provider.go

**TODO BEFORE MERGE:** 
Our status page has been updated with a new path. It also now reports a list of HCP components, rather than a single rollup component. This required some refactoring of our status page checker.
Now, when any single HCP component is reporting non-operational, the provider will the warning below with the statuses of all HCP components.
```
$  terraform plan        
╷
│ Warning: You may experience issues using HCP.
│ 
│   with provider["localhost/providers/hcp"],
│   on example.tf line 151, in provider "hcp":
│  151: provider "hcp" {}
│ 
│ HCP is reporting the following:
│ 
│ HCP Vault:       operational
│ HCP Packer:      operational
│ HCP API:         major_outage
│ HCP Portal:      operational
│ HCP Consul:      degraded_performance
│ 
│ Please check …
```

Update HCP status checker

---

.github/CODEOWNERS
CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Includes a [status checker update](https://github.com/hashicorp/terraform-provider-hcp/pull/298), doc updates, and dependency bumps.
Running one test is sufficient for these changes:
```
$ make testacc TESTARGS='-run=TestAccHvnOnly'
--- PASS: TestAccHvnOnly (143.32s)
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	143.667s
```

Prep 0.27.0

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Preps the release of 0.28.0, which includes an update to the Packer SDK to latest stable and dependency bumps.
```
$ make testacc TESTARGS='-run=TestAccHvnOnly'
--- PASS: TestAccHvnOnly (168.54s)
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	169.475s
$ make testacc TESTARGS='-run=TestAcc_dataSourcePacker'
--- PASS: TestAcc_dataSourcePackerIteration (9.86s)
--- PASS: TestAcc_dataSourcePackerImage (6.87s)
--- PASS: TestAcc_dataSourcePackerImage_revokedIteration (10.93s)
--- PASS: TestAcc_dataSourcePacker (64.01s)
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	34.334s
```

Prep 0.28.0

---

docs/guides/vault-performance-replication.md
examples/guides/vault_perf_replication/replication.tf
internal/provider/resource_aws_network_peering.go
internal/provider/resource_azure_peering_connection.go
internal/provider/resource_vault_cluster.go
internal/provider/resource_vault_cluster_test.go

No new features, just a couple minor improvements
- Recommend setting Vault performance secondary tiers via reference to primary
- Add 'computed: true' to Vault paths_filter
- Replace strings.EqualFold with ToLower in diff supression functions, since EqualFold was causing unexpected behavior
```release-note
NONE
```
```
...
```

Vault secondary tier by reference

---

internal/provider/resource_hvn_test.go

Quick fix and refactor of the HVN tests.
```
$ make testacc TESTARGS='-run=TestAccAzureHvnOnly'
--- PASS: TestAccAzureHvnOnly (280.39s)
PASS
```

Fix Azure HVN acceptance test

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Preps release of 0.32.0, which contains a bug fix for the HCP Status checker.
```
--- PASS: TestAccAwsHvnOnly (129.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	130.338s
```

Prep 0.32.0

---

docs/data-sources/packer_image.md
docs/data-sources/packer_iteration.md
internal/provider/data_source_packer_image.go
internal/provider/data_source_packer_image_iteration.go
internal/provider/data_source_packer_image_iteration_test.go
internal/provider/data_source_packer_image_test.go
internal/provider/data_source_packer_iteration.go
internal/provider/data_source_packer_iteration_test.go

HCP Packer will no longer return `error_revoked` so we are adding the `revoke_at` timestamp to all of our datasources. 
```release-note
* datasource/hcp_packer_image: Include `revoke_at` in the data source output. [GH-330]
* datasource/hcp_packer_iteration: Include `revoke_at` in the data source output. [GH-330]
* datasource/hcp_packer_image_iteration: Include `revoke_at` in the data source output. [GH-330]
```
```
--- PASS: TestAcc_dataSourcePacker (24.79s)
=== RUN   TestAcc_dataSourcePacker_revokedIteration
--- PASS: TestAcc_dataSourcePacker_revokedIteration …
```

Add revoke_at to HCP Packer datasources output

---

docs/resources/hvn.md
templates/resources/hvn.md.tmpl

- The `hcp_hvn` documentation was AWS VPC specific. These changes make them more generic to support multiple cloud providers.
- We also explained why you should specify production HVN CIDR block values.
```release-note
* docs: Refactor documentation for `hcp_hvn` resource [GH-337]
```
Closes #337

Refactor hcp hvn docs

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Prepares v0.34.0, which includes a networking doc clarification and the introduction of tracked `state` to our resources! Previously, failed resources were automatically removed from terraform state— leaving behind orphaned resources. Now, by tracking `state`, the provider will be better able to recover from failed resource creation.
```
$ make testacc
--- PASS: TestAccAwsPeering (722.57s)
--- PASS: TestAccTGWAttachment (770.96s)
--- PASS: TestAccHvnPeeringConnection (308.54s)
--- PASS: TestAccHvnRoute (947.37s)
--- PASS: TestAccAwsHvnOnly (165.44s)
--- PASS: TestAccAzureHvnOnly (298.79s)
--- PASS: TestAccConsulCluster (1592.92s)
--- PASS: TestAccConsulSnapshot (867.65s)
--- PASS: TestAccVaultCluster (3255.63s)
```
⚠️ NOTE: the Azure peering test result has …

Prep 0.34.0

---

docs/data-sources/packer_image.md
examples/data-sources/hcp_packer_image/data-source-alt.tf
examples/data-sources/hcp_packer_image/data-source.tf
internal/provider/data_source_packer_image.go
internal/provider/data_source_packer_image_test.go
templates/data-sources/packer_image.md.tmpl

Add a new channel attribute to the `hcp_packer_image` data source, so a user can fetch the latest image directly, without having to specify a companion `hcp_packer_iteration` data source to fetch the build ID from.
```release-note
* datasource/hcp_packer_image: allow `channel` attribute to get an image [GH-339]
```
```
$ make testacc TESTARGS='-run=TestAcc_dataSourcePackerImage_chan'
./scripts/gofmtcheck.sh: line 5: gofmt: command not found
TF_ACC=1 go test ./internal/... -v -run=TestAcc_dataSourcePackerImage_chan -timeout 210m
PASS
ok …
```

hcp_packer_image channel attribute support

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

```
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/consul	1.138s [no tests to run]
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/input	0.816s [no tests to run]
--- PASS: TestAccAwsHvnOnly (131.91s)
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	132.410s
...
```

Prep 0.35.0

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

```
$  make testacc TESTARGS='-run=TestAccAwsHvnOnly'
PASS
PASS
--- PASS: TestAccAwsHvnOnly (153.20s)
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	(cached)
...
```

Prep 0.36.0

---

internal/provider/resource_azure_peering_connection_test.go

Fixes a test that wasn't using configured Azure IDs.
```release-note
FIXES:
* resource/azure_peering: fix acceptance test [GH-nnnn]
```
This test is still having timeout issues - investigation is ongoing.

fix Azure peering acc test variables

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

```
$  make testacc TESTARGS='-run=TestAccAwsHvnOnly'
go: downloading github.com/go-openapi/strfmt v0.21.3
go: downloading go.mongodb.org/mongo-driver v1.10.0
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/consul	0.846s [no tests to run]
PASS
--- PASS: TestAccAwsHvnOnly (148.46s)
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider …
```

Prep 0.37.0

---

internal/clients/retry_request.go
internal/clients/retry_request_test.go
internal/provider/provider.go
internal/provider/provider_test.go

From time to time, the GET requests for fetching the organization and project will return a 502 or 504 which can cause E2E pipelines to fail. This PR addresses the issue by adding in some retry logic so if the 502s or 504s are temporary, we don't have to stop the whole pipeline in order to retry.
```release-note
* all: Add retry logic to the get organization and get project endpoints [GH-nnnn]
```
```
$ make testacc TESTARGS='-run=TestShouldRetryErrorCode'
TF_ACC=1 go test ./internal/... -v -run=TestShouldRetryErrorCode -timeout 210m
? …
```

TCE-1655: Retry failed GET organization and project requests

---

.github/CODEOWNERS

Fixes codeowners which had errors after a recent team name update.

update codeowners with team name

---

docs/data-sources/aws_network_peering.md
docs/data-sources/azure_peering_connection.md
internal/clients/peering.go
internal/provider/data_source_aws_network_peering.go
internal/provider/data_source_azure_peering_connection.go

Occasionally we get what look like timeouts while waiting on Azure peerings to flip to ACTIVE:
```
TestE2E_BasicAzure 2022-07-29T17:56:40Z logger.go:66: module.hcp_peering.data.hcp_azure_peering_connection.peering: Still reading... [19m50s elapsed]
TestE2E_BasicAzure 2022-07-29T17:56:50Z logger.go:66: 
TestE2E_BasicAzure 2022-07-29T17:56:50Z logger.go:66: Error: error waiting for peering connection (azure-e2e-68625cad-peer) to become 'ACTIVE'
TestE2E_BasicAzure 2022-07-29T17:56:50Z logger.go:66: 
TestE2E_BasicAzure 2022-07-29T17:56:50Z logger.go:66:   with module.hcp_peering.data.hcp_azure_peering_connection.peering,
TestE2E_BasicAzure 2022-07-29T17:56:50Z logger.go:66:   on .terraform/modules/hcp_peering/main.tf line 117, in data "hcp_azure_peering_connection" "peering": …
```

Log peering wait errors, use ReadTimeout in peering Data Sources

---

.github/workflows/terraform_provider.yml
contributing/README.md
go.mod
go.sum

Upgrades the provider to go version 1.18.
```release-note
* provider: upgrade to 1.18 [GH-365]
```
```
$ make testacc
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	5510.161s
```
Also ran a manual test with a Consul cluster, upgrading from the latest version to the provider build with these changes.
1. Initializing HVN + Consul cluster on 0.37.0:
```
$ terraform init
Initializing provider plugins...
- Finding hashicorp/hcp versions matching "~> 0.37.0"...
...
$ terraform apply
...
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```
2. Upgrading to local build with go upgrade:
```
$ terraform init
Initializing …
```

Upgrade go 1.18

---

docs/guides/consul-root-token.md
docs/resources/consul_cluster_root_token.md
internal/provider/resource_consul_cluster_root_token.go
templates/guides/consul-root-token.md.tmpl

Update docs regarding consul root tokens.
```release-note
NONE
```
N/A - only docs

Fix root token example and add clarification to resource doc

---

internal/clients/retry_request.go

There is an issue where URL Errors would get swallowed by the retry logic put in place for HTTP requests. This makes it hard to debug when a user may have an invalid login configuration so a check was put into place that identifies the type of error that was received and directs the user to a more helpful error message if necessary. 
Fixes: https://github.com/hashicorp/terraform-provider-hcp/issues/375
```release-note
* all: Prevents the app from crashing when a `*url.Error` is received while retrying HTTP requests. [GH-376]
```
```
PASS
ok …
```

Add error type check when retrying

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Preps the release of 0.42.0, which includes a critical fix to a panic that was happening in our retry helpers.
```
--- PASS: TestAccAwsHvnOnly (146.62s)
PASS
```

Prep 0.42.0

---

docs/guides/peering.md
examples/guides/peering/main.tf

```release-note
* docs : Update docs for hcp_hvn_route resource [GH-388]
```
```
PASS
PASS
PASS
=== RUN …
```

cited doc fix for issue #387

---

internal/provider/data_source_aws_network_peering.go
internal/provider/data_source_azure_peering_connection.go
internal/provider/resource_azure_peering_connection_test.go

Temporary fix to address an issue where timeouts aren't applied to a Data Source read. Relates to https://github.com/hashicorp/terraform-plugin-sdk/issues/1038
```release-note
* {azure data source}: {Replace ReadContext with ReadWithoutTimeout in the Azure and AWS peering connection} [GH-389]
```
```
...
```

Replace ReadContext with ReadWithoutTimeout

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Release 0.47.0
```
PASS
PASS
PASS
--- PASS: TestAccAwsHvnOnly (120.52s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider   120.872s …
```

Release 0.47.0

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Release 0.48.0
```
$ make testacc TESTARGS='-run=TestAccConsulCluster'
TF_ACC=1 go test ./internal/... -v -run=TestAccConsulCluster -timeout 210m
PASS
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/consul     0.737s [no tests to run]
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/input      0.207s [no tests to run]
=== RUN   TestAccConsulCluster
--- PASS: TestAccConsulCluster (1806.45s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider …
```

Release 0.48.0

---

docs/guides/auth.md
examples/guides/auth/_config_no_clients.tf
templates/guides/auth.md.tmpl

This PR includes an amendment to the provider's public authentication docs in support of the released automatic browser login feature. This documentation update addresses a doc request brought forward in our Issues backlog.
Jira Ticket - [Documentation for the browser OIDC login support](https://hashicorp.atlassian.net/browse/HCE-602)
Github Issue - [Provider documentation for browser login](https://github.com/hashicorp/terraform-provider-hcp/issues/409)
```release-note
* docs: Docs update to highlight optional browser login feature [GH-412]
```
```
...
```

Updates browser login documentation

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

This preps the release of 0.49.0, consisting of documentation updates and dependency bumps.
Testing:
```
--- PASS: TestAcc_dataSourcePacker (8.26s)
--- PASS: TestAcc_dataSourcePacker_revokedIteration (11.03s)
--- PASS: TestAcc_dataSourcePackerImage (7.02s)
--- PASS: TestAcc_dataSourcePackerImage_revokedIteration (9.77s)
--- PASS: TestAcc_dataSourcePackerImage_channelAndIterationIDReject (3.18s)
--- PASS: TestAcc_dataSourcePackerImage_channelAccept (5.58s)
--- PASS: TestAcc_dataSourcePackerIteration (5.31s)
--- PASS: TestAcc_dataSourcePackerIteration_revokedIteration (11.06s)
--- PASS: TestAccTGWAttachment (760.50s)
--- PASS: TestAccHvnRoute (781.40s)
--- PASS: TestAccAwsHvnOnly (130.40s)
--- PASS: TestAccAzureHvnOnly (419.06s)
--- PASS: TestAccHvnPeeringConnection (305.20s)
--- PASS: …
```

Release 0.49.0

---

.changelog/427.txt
internal/provider/resource_consul_cluster.go

In our E2E testing, we see Consul cluster delete times occasionally a bit above 25 minutes. Those clusters delete successfully, but the TF provider errors out on context cancellation. This increases the timeout from 25 minutes to 35 minutes, matching the Create timeout we already have.
I have not ran acceptance testing because this only increases the delete timeout value to match the existing create timeout, no other behavior changed.
```
...
```

Increase `hcp_consul_cluster` delete timeout to 35 min

---

.changelog/429.txt
.github/dependabot.yml
.github/workflows/create-dependabot-changelog.yml

Add a GitHub action that will create a changelog entry for dependabot PRs. This will also disable the changelog check for dependabot PRs by adding the pr/no-changelog label.
Proof of concept: https://github.com/hashicorp/cloud-tooling-automation-spike/pull/18

HCE-721 Add Auto Changelog for Dependabot

---

.github/workflows/create-dependabot-changelog.yml

Adjust the name of `dependabot` to the correct one: `dependabot[bot]`
This was confirmed with the GitHub API:
```
> gh api /repos/hashicorp/terraform-provider-hcp/pulls/431 --method GET
```
```json
{
"url": "https://api.github.com/repos/hashicorp/terraform-provider-hcp/pulls/431",
"id": 1164098932,
"node_id": "PR_kwDOE4g6Vc5FYr10",
"html_url": "https://github.com/hashicorp/terraform-provider-hcp/pull/431",
"diff_url": "https://github.com/hashicorp/terraform-provider-hcp/pull/431.diff",
"patch_url": "https://github.com/hashicorp/terraform-provider-hcp/pull/431.patch",
"issue_url": "https://api.github.com/repos/hashicorp/terraform-provider-hcp/issues/431",
"number": 431,
"state": "open",
"locked": false,
"title": "Bump github.com/hashicorp/hcp-sdk-go from 0.28.0 to 0.29.0",
"user": { …
```

HCE-721: Fix Dependabot Name

---

internal/provider/data_source_packer_image_iteration_test.go
internal/provider/data_source_packer_image_test.go
internal/provider/data_source_packer_iteration_test.go
internal/provider/resource_aws_network_peering_test.go
internal/provider/resource_aws_transit_gateway_attachment_test.go
internal/provider/resource_azure_peering_connection_test.go
internal/provider/resource_boundary_cluster_test.go
internal/provider/resource_hvn_peering_connection_test.go
internal/provider/resource_hvn_route_test.go
internal/provider/resource_hvn_test.go

To help with test cleanup in case of unexpected panics.
EDIT: Reverted the Consul change due to consistent creation timeout failures. Reaching out to Consul team to find out the issue.
```
$ make testacc
--- PASS: TestAcc_dataSourcePacker (13.14s)
--- PASS: TestAcc_dataSourcePacker_revokedIteration (11.51s)
--- PASS: TestAcc_dataSourcePackerImage_channelAndIterationIDReject (7.85s)
--- PASS: TestAcc_dataSourcePackerImage_channelAccept (5.79s)
--- PASS: TestAcc_dataSourcePackerIteration (5.48s)
--- PASS: TestAcc_dataSourcePackerIteration_revokedIteration (11.06s)
--- PASS: TestAccHvnPeeringConnection (305.60s)
--- PASS: TestAccAzureHvnOnly (281.41s)
--- PASS: TestAccAwsHvnOnly (113.52s)
--- PASS: TestAccHvnRoute (706.42s)
--- PASS: …
```

HCE-716: differentiate acceptance test IDs

---

.changelog/437.txt
internal/provider/resource_consul_cluster_test.go

This change adds unique cluster IDs to prevent reuse of identifiers and cluster name collision on test retries.
```
TF_ACC=1 go test ./internal/... -v -run=TestAccConsulCluster -timeout 210m
PASS
PASS
PASS
=== RUN   TestAccConsulCluster …
```

Unique Consul Cluster ID

---

.changelog/439.txt
docs/resources/consul_cluster.md
docs/resources/consul_cluster_root_token.md
internal/provider/resource_consul_cluster.go
internal/provider/resource_consul_cluster_root_token.go

Currently, the tokens generated by HCP Consul are never deleted or invalidated by HCP processes.
Update consul docs related to #420 .
Is there anything else I need to do to update docs? I see there are markdown files related to them, are those autogenerated?
This was just a docs change, so didn't run tests.

Correct consul cluster and root token docs

---

.changelog/448.txt
internal/provider/provider_test.go

Quick fix. During the Preconfig step (prior to `plan` or `apply`), the HCP provider checks the HCP status page and returns a warning if there is any degraded performance or outage. The acceptance tests were exiting on any error during the preconfig step, so it was failing on the status page warnings. This PR checks the `Severity` of the returned error (type `Diagnostic`) and allows tests to proceed despite any warnings.
```
$ make testacc TESTARGS='-run=Packer'
--- PASS: TestAcc_dataSourcePacker (7.36s)
--- PASS: TestAcc_dataSourcePacker_revokedIteration (9.72s)
--- PASS: TestAcc_dataSourcePackerImage (6.20s)
--- PASS: TestAcc_dataSourcePackerImage_revokedIteration (8.97s)
--- PASS: TestAcc_dataSourcePackerImage_channelAndIterationIDReject (2.35s)
--- PASS: …
```

do not fail acceptance test when provider returns a warning

---

internal/provider/data_source_packer_image_iteration_test.go
internal/provider/data_source_packer_image_test.go

Previously, the revocation acceptance test would error because the data
source was configured to error when querying for a revoked image. That
logic has since been removed, and no longer errors. Instead the
attribute revoked_at is set to a valid revocation date, and the cloud
image id is set to the value stored in HCP Packer. This change updates
the test to reflect the new expected behavior and adds a clean step on
CheckDestroy to ensure no test images are left in the registry under
test.
```
$  make testacc TESTARGS='-run=Packer'
--- PASS: TestAcc_dataSourcePacker (9.75s)
=== RUN   TestAcc_dataSourcePacker_revokedIteration
--- PASS: TestAcc_dataSourcePacker_revokedIteration (13.88s)
=== RUN   TestAcc_dataSourcePackerImage …
```

Update Revocation Acceptance test case to clean up on exit

---

docs/resources/packer_channel.md
examples/resources/hcp_packer_channel/resource_assignment.tf
examples/resources/hcp_packer_channel/resource_using_latest_channel.tf
internal/clients/packer.go
internal/provider/resource_packer_channel.go
internal/provider/resource_packer_channel_test.go

The current implementation relies on the use of an extra iteration_assignment block to denote what iteration to assign to a channel. Instead of defining a separate block this change uses the single iteration block to denote the state of a channel. Modifying the iteration block will trigger the respective updates to the state of a channel. Removing the iteration block will remove the assigned iteration from the channel.
Potentially Supersedes #435 
```
$ make testacc TESTARGS='-run=TestAccPackerChannel'
...
```

[HPR-859] Update resource schema to use a single iteration block

---

.changelog/457.txt
docs/resources/packer_channel.md
templates/resources/packer_channel.md.tmpl

The hcp_packer_channel is being released as a beta to allow for user feedback. This change adds the public beta call out within the resource documentation. 
N/A
```
...
```

resource/hcp_packer_channel: Label resource as public beta

---

.changelog/455.txt
docs/data-sources/consul_cluster.md
docs/resources/consul_cluster.md
go.mod
go.sum
internal/provider/data_source_consul_cluster.go
internal/provider/resource_consul_cluster.go
internal/provider/resource_consul_cluster_test.go
internal/provider/validators.go
internal/provider/validators_test.go

- Adding a new field `ip_allowlist` to the `hcp_consul_cluster` resource to support IP Allowlisting - a Block List (list of objects).
- Validation Rules:
- No duplicate CIDR allowed
- Maximum of 3 IP Allowlist entries allowed
- Max length of 255 characters for the description field
```
~/Github/HashiCorp/terraform-provider-hcp CC-4083/ip-allowlist* ⇡ 16m 2s
❯ make testacc TESTARGS='-run=TestAccConsulCluster'
TF_ACC=1 go test ./internal/... -v -run=TestAccConsulCluster -timeout 210m
PASS …
```

[CC-4083] IP Allowlist Feature for Consul Cluster

---

.changelog/462.txt
docs/resources/packer_channel.md
internal/provider/resource_packer_channel.go

A few of the output attributes were incorrectly documented. This change updates the documentation to reflect the channel resource under management.
N/A - only documentation changes within this pull request.
```
TF_ACC=1 go test ./internal/... -v -run=TestAcc_*Packer -timeout 210m -parallel=10
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/clients    0.188s [no tests to run]
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/consul     0.224s [no tests to run]
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/input      0.275s [no tests to run]
=== RUN   TestAccPackerChannel
--- PASS: TestAccPackerChannel …
```

resource/hcp_packer_channel: Fix documentation for incorrectly documented attributes

---

.changelog/465.txt
internal/provider/resource_vault_cluster_test.go

Add cluster scaling tests for Azure
```
$  TF_LOG_PATH=scale.out.text TF_LOG=TRACE TF_ACC=1 go test ./internal/... -parallel 20 -v -run=TestAccVaultClusterAzure -timeout 240m
PASS
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/consul	0.436s [no tests to run]
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/input	0.325s [no tests to run]
=== RUN   TestAccVaultClusterAzure
=== PAUSE TestAccVaultClusterAzure
=== CONT  TestAccVaultClusterAzure
--- PASS: TestAccVaultClusterAzure (3479.18s)
PASS
ok …
```

HVT-2807 Add cluster scaling tests for Azure

---

docs/data-sources/aws_network_peering.md
docs/resources/aws_network_peering.md
internal/provider/data_source_aws_network_peering.go
internal/provider/resource_aws_network_peering.go

This code includes changes to allow associated project ID to be optionally read from either the provider config or AWS network peering's config directly. Primary test coverage for helpers used and changes made were tested using the steps in GH-460 - [Add project ID to HVN](https://github.com/hashicorp/terraform-provider-hcp/pull/460).
Jira 🎟️ :
[Add project_id to AWS peering](https://hashicorp.atlassian.net/jira/software/c/projects/HCE/boards/550?selectedIssue=HCE-778)
```
$ make testacc TESTARGS='-run=AwsPeering'    
TF_ACC=1 go test ./internal/... -v -run=AwsPeering -timeout 210m -parallel=10
PASS
ok …
```

Add project ID to AWS network peering

---

.changelog/480.txt
docs/resources/consul_cluster.md
docs/resources/vault_cluster.md
internal/provider/resource_consul_cluster.go
internal/provider/resource_vault_cluster.go

Updates the pricing URL for [vault](https://www.hashicorp.com/products/vault/pricing) and [consul](https://www.hashicorp.com/products/consul/pricing). Replaced https://cloud.hashicorp.com/pricing/vault and https://cloud.hashicorp.com/pricing/consul urls which are broken.

update pricing url: replaced broken links

---

docs/data-sources/vault_cluster.md
docs/resources/vault_cluster.md
docs/resources/vault_cluster_admin_token.md
internal/provider/data_source_vault_cluster.go
internal/provider/resource_vault_cluster.go
internal/provider/resource_vault_cluster_admin_token.go

Add project_id to Vault Cluster resource.

HCE-793: Add Project ID to Vault Cluster

---

internal/provider/peering.go
internal/provider/peering_test.go
internal/provider/resource_aws_network_peering.go
internal/provider/resource_aws_transit_gateway_attachment.go
internal/provider/resource_azure_peering_connection.go
internal/provider/resource_boundary_cluster.go
internal/provider/resource_consul_cluster.go
internal/provider/resource_hvn.go
internal/provider/resource_hvn_peering_connection.go
internal/provider/resource_hvn_route.go
internal/provider/resource_packer_channel.go
internal/provider/resource_vault_cluster.go

Allow Project IDs to be explicitly set when importing resources.
```
--- PASS: TestAccAwsHvnOnly (139.13s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider   139.477s
...
```

HCE-345: Allow Project ID on Terraform Import

---

.changelog/510.txt
go.mod
go.sum
internal/clients/vault_cluster.go
internal/provider/resource_vault_cluster.go

Update `hcp-go-sdk` to the latest version. Found breaking change with the vault API and applied client side updates to remediate the issues.
```
➜  terraform-provider-hcp git:(update-hcp-sdk) ✗ make testacc TESTARGS='-run=TestAccVaultClusterAWS'
TF_ACC=1 go test ./internal/... -v -run=TestAccVaultClusterAWS -timeout 360m -parallel=10
PASS
PASS
PASS
ok …
```

Update hcp sdk

---

.changelog/500.txt
docs/data-sources/boundary_cluster.md
docs/resources/boundary_cluster.md
examples/resources/hcp_boundary_cluster/resource.tf
internal/clients/boundary_cluster.go
internal/provider/data_source_boundary_cluster.go
internal/provider/resource_boundary_cluster.go
internal/provider/resource_boundary_cluster_test.go
internal/provider/resource_vault_cluster.go

Extends the HCP Boundary cluster resource to support maintenance window configuration. The maintenance window configuration sets the period when cluster upgrades to take place.
HCP Boundary admins can configure either `automatic` or `scheduled` upgrade type. `Scheduled` are customer specified and require a day of the week, start and end hours.
```
➜  terraform-provider-hcp git:(uruemu/ICU-8995) ✗ make testacc TESTARGS='-run=TestAccBoundaryCluster'
TF_ACC=1 go test ./internal/... -v -run=TestAccBoundaryCluster -timeout 360m -parallel=10
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/clients …
```

HCP Boundary maintenance window config

---

.changelog/513.txt
docs/resources/packer_channel.md
templates/resources/packer_channel.md.tmpl

This resource is no longer in beta
I did not run acceptance tests on this change since it is only a docs change

[HPR-1139] Remove beta label from HCP Packer channel resource

---

.changelog/515.txt
docs/resources/hvn_route.md
internal/provider/resource_hvn.go
internal/provider/resource_hvn_route.go
internal/provider/validators.go
internal/provider/validators_test.go
templates/resources/hvn_route.md.tmpl

* The network service has been updated to allow creation of HVN routes to [RFC 6598](https://datatracker.ietf.org/doc/html/rfc6598#section-7). We need to support this functionality through the `hcp_hvn_route` resource as well.
* This change updates the validation used on the `destination_cidr` attribute of the `hcp_hvn_route` resource to allow the additional network range (`100.64.0.0/10`)
* https://github.com/hashicorp/cloud-network/pull/1122
* https://github.com/hashicorp/cloud-ui/pull/6159
```
...
```

IFACE-1880: Enable RFC 6598 CIDR Range for HVN Route

---

.changelog/520.txt
.github/workflows/prerelease.yml

* Due to ongoing [E2E failures](https://github.com/hashicorp/terraform-provider-hcp/actions/runs/5138483891/jobs/9247870935) (incident related), we are unable to create a new release of the provider.
* This PR adds an input to the workflow_dispatch trigger to allow bypassing the e2e steps. The E2Es are run by default, switching `skip-e2e: true` will bypass the tests.
```
...
```

Allow `prerelease` E2E bypass

---

.changelog/521.txt
docs/resources/packer_channel.md
examples/resources/hcp_packer_channel/resource_assignment.tf
internal/clients/packer.go
internal/provider/resource_packer_channel.go
templates/resources/packer_channel.md.tmpl

Previously, when no iteration block existed on `hcp_packer_channel`, the provider would treat external management of the channel's iteration assignment as configuration drift and the assignment would be removed on next apply. Now, the channel's assigned iteration is ignored when there is no iteration block present. In use cases where users may want to force a channel to have no assigned iteration, they can use a zero value for one of the attributes in the iteration block.
Additionally, these changes enhance plans by populating the 2 unset iteration block attributes with the data associated with the 1 set attribute. This improves visibility in cases where the iteration associated with the chosen attribute may change due to external modifications (ex: deletion of an iteration with …

HPR-1177: Assigned iteration should not be forced to be null when no iteration block is present

---

.changelog/522.txt
docs/data-sources/hvn_peering_connection.md
docs/data-sources/hvn_route.md
docs/resources/hvn_peering_connection.md
docs/resources/hvn_route.md
examples/data-sources/hcp_hvn_peering_connection/data-source.tf
examples/data-sources/hcp_hvn_peering_connection/variables.tf
internal/provider/data_source_azure_peering_connection.go
internal/provider/data_source_consul_agent_helm_config.go
internal/provider/data_source_consul_agent_kubernetes_secret.go
internal/provider/data_source_hvn_peering_connection.go
internal/provider/data_source_hvn_route.go
internal/provider/resource_azure_peering_connection.go
internal/provider/resource_boundary_cluster.go
internal/provider/resource_consul_cluster_root_token.go
internal/provider/resource_hvn_peering_connection.go
internal/provider/resource_hvn_peering_connection_test.go
internal/provider/resource_hvn_route.go
internal/provider/resource_packer_channel.go
internal/provider/resource_vault_cluster_admin_token.go

Fixes missing/incorrect resource-specific, resource-level `project_id` implementations for:
- `hcp_packer_channel`
- Read (was missing)
- Update (was missing)
- Delete (was missing)
- `hcp_azure_peering_connection`
- Create (was incorrect, assumed HVN used provider-level value)
- `data.hcp_azure_peering_connection`
- Read (was incorrect, assumed HVN used provider-level value)
- `hcp_hvn_route`
- Read (was missing)
- `hcp_vault_cluster_admin_token`
- Read (was missing)
- Logging (was incorrect, didn't pull from `loc`)
- `hcp_consul_cluster_root_token`
- Read (was missing)
- Delete (was missing)
- `data.consul_agent_helm_config`
- Read (had redundant code)
- `hcp_boundary_cluster`
- Update (was incorrect, implementation existed but was not used)
Deprecates some unnecessary fields on some …

HCPF-704: Fix Missing/Incorrect Resource-level `project_id` Implementations

---

docs/index.md
templates/index.md.tmpl

The docs were pulling an image from cloud.hashicorp.com. We recently moved that domain, so this PR fixes the image sourcing. 
No acceptance testing necessary, but I did check that the image link renders well by putting the markdown into https://registry.terraform.io/tools/doc-preview

[docs] Fix link to architecture image now that cloud website has moved

---

.changelog/533.txt
internal/provider/data_source_packer_image.go
internal/provider/data_source_packer_image_iteration_test.go
internal/provider/data_source_packer_image_test.go
internal/provider/data_source_packer_iteration_test.go

Fixes #526 
Fixes #496 
- Fixes a bug where the image data source crashes when the channel it points to doesn't have an iteration assigned
- Adds a unit test for an empty channel 
```
$ make testacc TESTARGS='-run=TestAcc.*PackerImage.* -test.v'
TF_ACC=1 go test ./internal/... -v -run=TestAcc.*PackerImage.* -test.v -timeout 360m -parallel=10
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/clients    0.468s [no tests to run]
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/consul     0.934s [no tests to run]
PASS
ok …
```

HPR-1208: Fix panic when `hcp_packer_image` points to an empty channel

---

.changelog/537.txt
docs/data-sources/consul_cluster.md
docs/resources/consul_cluster.md
internal/provider/data_source_consul_cluster.go
internal/provider/resource_consul_cluster.go

This is just a docs change. This adds the `premium` tier to Consul Cluster: https://www.hashicorp.com/products/consul/pricing
It's already supported in the backing Go code as an enum:
```
// HashicorpCloudConsul20210204ClusterConfigTierPREMIUM captures enum value "PREMIUM"
HashicorpCloudConsul20210204ClusterConfigTierPREMIUM HashicorpCloudConsul20210204ClusterConfigTier = "PREMIUM"
```
JIRA: https://hashicorp.atlassian.net/browse/CC-5321
```
...
```

[CC-5321] Add premium to Consul Cluster tier's description

---

.github/CODEOWNERS
internal/provider/provider.go
internal/provider/statuspage.go

Currently, adding a new resource/datasource requires approval from @hashicorp/core-sre because they own the Statuspage.io configuration in `provider.go`, where new resources are configured.
- Moves the Statuspage.io config to a new dedicated file
- Updates CODEOWNERS respectively
- @hashicorp/experiences-platform doesn't exist, so it is removed
- @hashicorp/core-sre removed from `provider.go` and added to `statuspage.go`
```
$ make testacc TESTARGS='-run=Test.*Provider.* -test.v'
TF_ACC=1 go test ./internal/... -v -run=Test.*Provider.* -test.v -timeout 360m -parallel=10
PASS
ok …
```

Move Statuspage.io config to a dedicated file

---

.changelog/542.txt
internal/clients/retry_request.go

If the error is returned from hcp-sdk is not known then wrap it before returning instead of swallowing it completely. Currently, its impossible to decipher what went wrong just from logs.
https://gist.github.com/aidan-mundy/bcda1f2c7be52d3a2e152d5ab9d3d622
The three failing tests have been persistent failures for a while, and are unrelated to this PR.

Do not swallow sdk error

---

.changelog/545.txt
internal/clients/packer.go
internal/provider/test_helpers_packer_test.go

- Resolves panics when Packer client helpers receive unexpected error formats
- Error is now returned if we fail to cast to the expected error format
Changes should improve visibility into #538 if it recurs
```
$ make testacc TESTARGS='-run=Test.*Packer.* -test.v'
TF_ACC=1 go test ./internal/... -v -run=Test.*Packer.* -test.v -timeout 360m -parallel=10
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/clients    0.456s [no tests to run]
PASS
testing: warning: no tests to …
```

HPR-1123: Resolve panics when Packer client helpers receive unexpected error formats

---

internal/provider/provider_test.go
internal/provider/resource_packer_channel_assignment_test.go
internal/provider/test_helpers_test.go

The testing system will not run `CheckDestroy` for tests that don't generate a non-empty state.
- Adds a dummy testing-only provider and dummy testing-only resource that can be used to force the testing system to generate a non-empty state without performing any real actions.
- This could be done using the `null` provider instead, but would require extra configuration from tests that need to use it. This solution adds code that is effectively a one-liner fix for tests that run into this issue. 
- Fixes an issue where one of the channel assignment tests wasn't running `CheckDestroy` which is used to clean up the bucket created in `PreCheck`, leading to environment pollution with buckets created in prior testing runs.
```
$ make testacc …
```

Fix test cleanup for `ChannelAssignment_HCPManagedChannelErrors`

---

.changelog/544.txt
docs/data-sources/boundary_cluster.md
docs/resources/boundary_cluster.md
internal/provider/data_source_boundary_cluster.go
internal/provider/resource_boundary_cluster.go
internal/provider/resource_boundary_cluster_test.go

Adds cluter `Tier` configuration for HCP Boundary clusters. A cluster can either be `PLUS` OR `STANDARD` tier.
More about HCP Boundary tiers: https://www.hashicorp.com/products/boundary/pricing
```
➜  terraform-provider-hcp git:(uruemu/ICU-9830) ✗ make testacc TESTARGS='-run=TestAccBoundaryCluster'
TF_ACC=1 go test ./internal/... -v -run=TestAccBoundaryCluster -timeout 360m -parallel=10
PASS
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/consul     (cached) [no tests …
```

Add tier configuration for HCP Boundary

---

.changelog/554.txt
internal/provider/resource_boundary_cluster.go
internal/provider/resource_boundary_cluster_test.go

Builds upon #544. Makes the tier configration case insensitive
```
...
```

Case insensitive HCP Boundary tier configuration 

---

.github/workflows/test.yml

- Add concurrency group to test workflow
- Prevents multiple acceptance testing jobs from running at the same time, which could cause unexpected outcomes.

Add concurrency group to test workflow

---

go.mod
go.sum

- Bump github.com/hashicorp/hcp-sdk-go from 0.49.0 to 0.54.0
[Test Workflow](https://github.com/hashicorp/terraform-provider-hcp/actions/runs/5651160290/job/15308785105)

Bump github.com/hashicorp/hcp-sdk-go from 0.49.0 to 0.54.0

---

.github/workflows/prerelease.yml

- Stops the `Prerelease` workflow if the Changelog for the released version would be empty.
- Prevents automated releases from being triggered when the only changes since the last release are meta changes (like this PR) that don't affect the provider functionality (and thus don't get a changelog). 
- Prevents releases from being triggered when changes are made that affect the provider functionality, but no changelogs were added since the last release. 
https://github.com/hashicorp/terraform-provider-hcp/actions/runs/5672099858
https://github.com/hashicorp/terraform-provider-hcp/actions/runs/5672099858/job/15376976887

Stop `Prerelease` workflow if the Changelog for the released version would be empty

---

.github/dependabot.yml
.github/workflows/changelog-check.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/sync-internal-and-public.yml
.github/workflows/terraform_provider.yml
.github/workflows/test.yml

Replaces #498
- Pins all Actions to the latest TSCCR trusted sha
- Removes the dependabot config for Actions. Version updates will be handled by https://github.com/hashicorp/security-tsccr/pull/625

SEC-090: Automated trusted workflow pinning

---

.changelog/569.txt
docs/data-sources/packer_image_iteration.md
internal/provider/data_source_packer_image_iteration.go
templates/data-sources/packer_image_iteration.md.tmpl

- Deprecates `data.hcp_packer_image_iteration`
```
$ make testacc TESTARGS='-run=Test.*dataSourcePacker.* -test.v' 
TF_ACC=1 go test ./internal/... -v -run=Test.*dataSourcePacker.* -test.v -timeout 360m -parallel=10
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/clients    0.229s [no tests to run]
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/consul     0.158s [no tests to run]
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/input      0.115s [no tests to run]
=== RUN …
```

HPR-1231: Deprecate `data.hcp_packer_image_iteration`

---

.changelog/577.txt
docs/data-sources/vault_cluster.md
docs/resources/vault_cluster.md
internal/clients/vault_cluster.go
internal/provider/data_source_vault_cluster.go
internal/provider/resource_vault_cluster.go
internal/provider/resource_vault_cluster_const_test.go
internal/provider/resource_vault_cluster_test.go
internal/provider/validators.go

Updating the `hcp_vault_cluster` resource to have `proxy_endpoint` (writeable) and `vault_proxy_endpoint_url` (read-only) fields. The `proxy_endpoint` field allows users to toggle the proxy on/off for their cluster. This feature was released on Mon Aug 7 for HCP Vault Dedicated through the UI.
As part of this change, we are also refactoring `public_endpoint` updates to be grouped into `UpdateVaultClusterConfig` call and moving off of `UpdateVaultClusterPublicIps`. Please refer to the [ADR](https://docs.google.com/document/d/1wad3DHl8HN5AZW9VH2_sIGoZtosRpeCKxZ_BdJ0V42U/edit) for more details.
<details><summary>AWS</summary>
```zsh
$ make testacc TESTARGS='-run=TestAccVaultClusterAWS'
TF_ACC=1 go test ./internal/... -v -run=TestAccVaultClusterAWS -timeout …
```

Hvt 4182 http proxy for hcpv in hcp tfp

---

internal/provider/data_source_packer_image_test.go
internal/provider/data_source_packer_iteration_test.go

- Increase revocation time to account for parallelization pausing tests
- Fixes the two packer tests that are currently blocking releases
- Wasn't caught by original testing because packer tests run faster than the 5 minute revocation time, but the full test suite takes a few hours. Increased to 24 hours to give plenty of time.
Thank you @helenfufu for bringing this to my attention!
https://github.com/hashicorp/terraform-provider-hcp/actions/runs/5886473625/job/15964386346

Increase revocation time to account for parallelization pausing tests

---

.changelog/591.txt
internal/provider/resource_vault_plugin.go
internal/provider/resource_vault_plugin_test.go

Fixing acceptance test for `hcp_vault_plugin` resource by removing hard coded variables.
```
$ make testacc TESTARGS='-run=TestAccVaultPlugin'
TF_ACC=1 go test ./internal/... -v -run=TestAccVaultPlugin -timeout 360m -parallel=10
PASS
PASS
PASS
=== RUN …
```

fix test CI

---

.github/workflows/prerelease.yml

- Delay automatic weekly prereleases by 2 hour 
- Will be weekly on Wednesdays at 02:00 UTC (previously 00:00 UTC)
The release process currently takes ~4 hours (the vast majority from running acceptance tests). If code is merged to `main` during the release, the release can still succeed, but leaves the `main` branch in an incorrect state that requires manual intervention. This failure mode occurred during last week's release due to a merge from a US West coast engineer just after the start of the prerelease.
Automatic prereleases currently start at 00:00 UTC, which is 17:00 PDT / 16:00 PST (at or just before the end of normal working hours). Delaying by 2 hours provides a worst case start time of 18:00 PST (6 PM west coast US), and a worst case end time of ~08:15 CEST (8:15 AM central …

Push automatic prereleases back by 2 hours

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Currently we need to release a patch fix to a bug that went [out](https://github.com/hashicorp/terraform-provider-hcp/issues/603) in the `0.71.0`. 
```
...
```

Updates for a manual patch release

---

docs/data-sources/hvn.md
docs/data-sources/hvn_peering_connection.md
docs/data-sources/hvn_route.md
docs/guides/hvn-route-migration-guide.md
docs/resources/aws_network_peering.md
docs/resources/hvn_peering_connection.md
templates/data-sources/hvn.md.tmpl
templates/data-sources/hvn_peering_connection.md.tmpl
templates/data-sources/hvn_route.md.tmpl
templates/guides/hvn-route-migration-guide.md.tmpl
templates/resources/aws_network_peering.md.tmpl
templates/resources/hvn_peering_connection.md.tmpl

- Fixes problems missed/introduced by #585 
- Improper header formatting (header displays as part of page text and categorization is ignored)
- Templates not using `import.sh` in the `examples` folder
- Product-specific guides missing a product category

Fix HVN Docs

---

.changelog/622.txt
docs/guides/consul-federation.md
docs/guides/consul-root-token.md
docs/guides/consul-snapshots.md
docs/guides/hvn-route-migration-guide.md
docs/guides/packer-channel-management.md
docs/guides/packer-run-tasks-with-terraform.md
docs/guides/vault-admin-token.md
docs/guides/vault-performance-replication.md
docs/guides/vault-scaling.md
templates/guides/consul-federation.md.tmpl
templates/guides/consul-root-token.md.tmpl
templates/guides/consul-snapshots.md.tmpl
templates/guides/hvn-route-migration-guide.md.tmpl
templates/guides/packer-channel-management.md.tmpl
templates/guides/packer-run-tasks-with-terraform.md.tmpl
templates/guides/vault-admin-token.md.tmpl
templates/guides/vault-performance-replication.md.tmpl
templates/guides/vault-scaling.md.tmpl

- Remove subcategories from Guides to fix duplicate folders: https://registry.terraform.io/providers/hashicorp/hcp/0.72.1/docs

Remove subcategories from Guides

---

.changelog/638.txt
README.md

https://github.com/hashicorp/terraform-provider-hcp/pull/637 wil make 1.1.5 the minimum supported version of Terraform. This PR adds a changelog to preemptively inform users.
N/A

Deprecate pre-1.1.5 support

---

.changelog/642.txt
docs/resources/project.md
examples/resources/hcp_project/import.sh
internal/provider/resourcemanager/resource_project.go

Fixes a bug in project import where it was setting the resource_name instead of the resource_id
```
$ TF_ACC=1 go test -v -run TestAccProjectResource
=== RUN   TestAccProjectResource
--- PASS: TestAccProjectResource (21.89s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider/resourcemanager   22.301s
```

Fix project import

---

.changelog/644.txt
.github/workflows/changelog-check.yml

- Fixes incorrect changelog entry so deprecation will actually appear in generated changelog.

Deprecate support for Terraform < 1.1.5 (protocol v5) in advance of v6 support

---

.changelog/639.txt
.changelog/650.txt
docs/data-sources/vault_cluster.md
docs/resources/vault_cluster.md
internal/providersdkv2/data_source_vault_cluster.go
internal/providersdkv2/resource_vault_cluster.go
internal/providersdkv2/resource_vault_cluster_config_test.go

The original PR that adds support for New Relic as an observability provider was merged before the provider was released. This PR reverts the original PR so that these changes aren't in `main` while the provider is not yet available

Revert "Add support for newrelic observability on vault_cluster resource"

---

.changelog/656.txt
internal/provider/iam/resource_workload_identity_provider.go

Fixes an issue where we required a trailing slash on the issuer_uri. This is an unnecessary restriction as the issuer can include or not include it. For example the HCP issuer includes it but the TFC issuer doesn't.
https://hashicorp.atlassian.net/browse/HCPIE-809
```
$ TF_ACC=1 go test -v
=== RUN   TestAccServicePrincipalDataSource
--- PASS: TestAccServicePrincipalDataSource (10.84s)
=== RUN   TestAccServicePrincipalKeyResource
--- PASS: TestAccServicePrincipalKeyResource (42.48s)
=== RUN   TestAccServicePrincipalResource_Project
--- PASS: TestAccServicePrincipalResource_Project (21.88s)
=== RUN   TestAccServicePrincipalResource_ExplicitProject
--- PASS: TestAccServicePrincipalResource_ExplicitProject (11.78s)
=== RUN …
```

Don't require trailing slash on issuer_uri

---

.changelog/657.txt
docs/resources/iam_workload_identity_provider.md
examples/resources/hcp_iam_workload_identity_provider/resource_azure.tf
examples/resources/hcp_iam_workload_identity_provider/resource_gcp.tf

Fixes workload identity examples to use proper values `conditional_access` and `allowed_audiences`.

Fix some workload identity examples

---

.github/workflows/changelog-check.yml

- Fix changelog not re-checked when `pr/no-changelog` label is removed

Fix changelog not re-checked when `pr/no-changelog` label is removed

---

.changelog/666.txt
go.mod
go.sum
internal/clients/client.go

The new version of the hcp-sdk-go did remove the implicit login on initialization. This change re-introduce the login by explicitly fetching credentials during the client initialization.
The change also introduces the ability to provide configuration via environment variables, which will allow credentials to be provided via environment variable (either directly or via a creds file).
Output from acceptance testing: 
(Any acceptance test should suffice to verify the functionality).
```
➜ make testacc TESTARGS='-run=TestAccProjectResource'
TF_ACC=1 go test ./internal/... -v -run=TestAccProjectResource -timeout 360m -parallel=10
? …
```

Update hcp-sdk-go and enable environment variable based configuration

---

.changelog/672.txt
docs/index.md
internal/clients/client.go
internal/provider/provider.go
internal/providersdkv2/provider.go

Add support for authenticating the provider using credential files. This will allow future integration with [Terraform Cloud Dynamic Credentials](https://developer.hashicorp.com/terraform/cloud-docs/workspaces/dynamic-provider-credentials).
Ran the provider with and confirmed it was authenticated:
* A valid credential file
* Client ID  / Client Secret
* Nothing set and browser was opened.
* Tested the new validation rules work.

Add support for credential files

---

internal/clients/client.go

The HCP integration tests set config via Env vars. This change brings back the old behavior, where we always source from env vars and then apply any explicit configuration.
```
$  TF_ACC=1 go test -v
=== RUN   TestAccServicePrincipalDataSource
--- PASS: TestAccServicePrincipalDataSource (15.67s)
=== RUN   TestAccServicePrincipalKeyResource
--- PASS: TestAccServicePrincipalKeyResource (35.46s)
=== RUN   TestAccServicePrincipalResource_Project
--- PASS: TestAccServicePrincipalResource_Project (8.91s)
=== RUN   TestAccServicePrincipalResource_ExplicitProject
--- PASS: TestAccServicePrincipalResource_ExplicitProject (5.27s)
=== RUN   TestAccServicePrincipalResource_Organization
--- PASS: TestAccServicePrincipalResource_Organization (5.73s)
=== RUN …
```

Always check env when building HCP Client

---

.changelog/678.txt
docs/data-sources/packer_iteration.md
docs/resources/packer_channel_assignment.md
internal/providersdkv2/data_source_packer_iteration.go
internal/providersdkv2/resource_packer_channel_assignment.go

- Deprecate to-be-removed Iteration attributes
- `data.hcp_packer_iteration.incremental_version`
- `hcp_packer_channel_assignment.iteration_version`
- `hcp_packer_channel_assignment.iteration_id`

HPR-1512: Deprecate to-be-removed Iteration attributes

---

internal/providersdkv2/resource_azure_peering_connection_test.go

* Prerelease pipeline is failing during azure peering test(s). Due to the tests not closely matching between CI / Internal tests, this PR refactors them to share as much of the same logic as possible. (The only difference should be the Azure AD service principal resources not being used for Internal tests.)
* Separates the tests to be individually-named go tests rather than test steps running the same test.
```sh
make testacc TESTARGS='-run=TestAccAzurePeeringConnectionInternal'
TF_ACC=1 go test ./internal/... -v -run=TestAccAzurePeeringConnectionInternal -timeout 360m -parallel=10
?   	github.com/hashicorp/terraform-provider-hcp/internal/clients/iampo …
```

Azure Peering Connection Test Updates

---

internal/providersdkv2/resource_aws_network_peering_test.go
internal/providersdkv2/resource_aws_transit_gateway_attachment_test.go

* E2E tests for AWS Peering and TGW Attachment are failing [during import test](https://github.com/hashicorp/terraform-provider-hcp/actions/runs/7168796630/job/19517751233#step:8:436) due to the state changing from PENDING_ACCEPTANCE to ACTIVE.
* This PR updates the import test to ignore that attribute.
```sh
make testacc TESTARGS='-run=TestAccAwsPeering'
TF_ACC=1 go test ./internal/... -v -run=TestAccAwsPeering -timeout 360m -parallel=10
?   	github.com/hashicorp/terraform-provider-hcp/internal/provider	[no test files]
? …
```

AWS Peering / TGW Attachment Test Update

---

.changelog/691.txt
docs/index.md
internal/clients/client.go
internal/provider/provider.go
internal/providersdkv2/provider.go

Support authenticating the provider using workload identity token's passed via file. This avoids the need to create a credential file to simplify the UX in certain scenarios.
I have tested the changes manually by having the provider authenticate using the new configuration block and tested that the provider errors if given conflicting ways to authenticate.

Provider accepts workload identity token via filepath HCPID2-1948

---

.github/workflows/prerelease.yml

- Change push order in Prerelease workflow to prevent releases desyncing from `main` if the push to `main` fails

Prevent releases desyncing from `main` if push to `main` fails

---

internal/provider/logstreaming/resource_hcp_log_streaming_destination_test.go

updating the test endpoint in the `hcp log streaming destination` tests to pass tls validation
<details>
<summary>TestAccHCPLogStreamingDestinationSplunk</summary>
```sh
$ make testacc TESTARGS='-run=TestAccHCPLogStreamingDestinationSplunk'
TF_ACC=1 go test ./internal/... -v -run=TestAccHCPLogStreamingDestinationSplunk -timeout 360m -parallel=10
?       github.com/hashicorp/terraform-provider-hcp/internal/clients/iampolicy  [no test files]
PASS
PASS
ok …
```

update log streaming destination test

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

This change is an attempt to re-release v0.81.1 as a minor release since it contains breaking changes. 
The provider release has been removed from the registry, the release and tag for 0.81.1 have also been deleted. 
- Revert "updated CHANGELOG.md" for 0.81.1
- Revert "updated documentation" for 0.81.1

Revert generated CHANGES from incorrect path release

---

.changelog/749.txt
docs/resources/packer_channel_assignment.md
examples/resources/hcp_packer_channel_assignment/resource.tf

Docs-only change:
Updates the `hcp_packer_channel_assignment` resource example to the current syntax (removing/replacing deprecated attributes).

Update example for hcp_packer_channel_assignment

---

.changelog/748.txt
internal/provider/project_helpers.go

We recently introduced no-role access which allows a user to become member of the org without access to any project. If such a user tries to use the provider then it will panic because the provider expects to have at least one project in `project.List` response which in this case will be empty array. Instead of panicing, error out saying the provider needs access to at least one project.
```sh
...
```

Error out if creds has no project access

---

.changelog/750.txt
internal/provider/vaultsecrets/resource_vault_secrets_secret.go
internal/provider/vaultsecrets/resource_vault_secrets_secret_test.go

Fixing the validation rules for HCP Vault Secrets app and secret names to match what we have on the server.
Fixes #728

[HCP Vault Secrets] fix app & secret name validation

---

internal/clients/client.go
internal/provider/iam/data_group.go
internal/provider/iam/data_group_test.go
internal/provider/provider.go

This PR includes changes to implement a groups data source and test coverage. Once implementation of the groups resource is completed, test coverage will be updated to CRUD a group with terraform, then point the data source to the generated resource.
Jira 🎟️ : Data Source: Group - [HCPIE-1020](https://hashicorp.atlassian.net/browse/HCPIE-1020)
- [ ❌ ] Are there any feature flags that are required to use this functionality?
- [✅  ] Have you added an acceptance test for the functionality being added?
- [✅ ] Have you run the acceptance tests on this branch?
Test coverage will be updated to point to a generated resource as per standard convention once groups resource implementation is completed. Currently test coverage points to my personal group as a proof of concept and to allow …

Group Data Source 

---

.github/workflows/release.yml

Github actions `upload-artifact` and `download-artifact` require the same major version for compatibility. With changes from https://github.com/hashicorp/terraform-provider-hcp/pull/747, only `upload-artifact` was upgraded, which caused issues when trying to run the `download-artifact` action [example](https://github.com/hashicorp/terraform-provider-hcp/actions/runs/7993028693).
https://github.com/hashicorp/terraform-provider-hcp/pull/747 upgraded `actions/upload-artifact` from v3 -> v4, but `hashicorp/ghaction-terraform-provider-release/.github/workflows/hashicorp.yml@v2` uses `actions/download-artifact` v3. We are upgrading to `hashicorp/ghaction-terraform-provider-release/.github/workflows/hashicorp.yml@v3` because it uses `actions/download-artifact` v4. 
Output from acceptance …

Upgrade release github action to use actions/download-artifact@v4

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Re-attempting to release v0.83.0 because it [failed to fully release](https://github.com/hashicorp/terraform-provider-hcp/actions/runs/7993028693) due to issue that was fixed in https://github.com/hashicorp/terraform-provider-hcp/pull/761 . 
- deleted the v0.83.0 tag on github
- reverting the changelog and documentation commits so that the pre-release workflow can be re-run successfully
```sh
...
```

Redo v0.83.0 undo changelog docs

---

go.mod
go.sum

Follow up to https://github.com/hashicorp/terraform-provider-hcp/pull/767 where the sdk goes from 0.85->0.86, here we bump to the latest of 0.87.0 for hcp-sdk-go. This will unblock the waypoint team.

Bump hcp-sdk-go to 0.87.0

---

.changelog/793.txt
internal/provider/project_helpers.go
internal/providersdkv2/provider.go

Updated the provider's logic to handle zero or multiple organizations associated with configured credentials. Added diagnostics to inform the user when no organizations or multiple organizations are found. Now, it prompts an error, requiring users to specify a particular organization in the HCP provider config block.
```sh
...
```

Handle multiple organizations for credentials

---

.changelog/802.txt
internal/clients/logs.go
internal/provider/logstreaming/resource_hcp_log_streaming_destination.go
internal/provider/logstreaming/resource_hcp_log_streaming_destination_test.go

Adding in-place update functionality to the `HCP Log Streaming Destination` resource.  [IFACE-2608](https://hashicorp.atlassian.net/browse/IFACE-2608)
<details>
<summary>TestAccHCPLogStreamingDestinationCloudwatch</summary>
```sh
$ make testacc TESTARGS='-run=TestAccHCPLogStreamingDestinationCloudwatch'
TF_ACC=1 go test ./internal/... -v -run=TestAccHCPLogStreamingDestinationCloudWatch -timeout 360m -parallel=10
=== RUN   TestAccHCPLogStreamingDestinationCloudWatch
--- PASS: TestAccHCPLogStreamingDestinationCloudWatch (6.36s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider/logstreaming      7.483s
```
</details>
<details> …

Add in-place update to HCP Log Streaming Destination

---

internal/provider/waypoint/resource_waypoint_add_on.go

Adds `project_id` and `organization_id` to the `AddOn` resource. 
Note that this PR is opened against a branch

Update AddOn schema/model to include project_id, organization_id

---

internal/provider/waypoint/resource_waypoint_add_on_definition_test.go
internal/provider/waypoint/resource_waypoint_application_template_test.go

HCP waypoint now tries to validate the no code modules being used, so we need to update our tests

update tests to use real tf no-code modules

---

.changelog/814.txt
.github/CODEOWNERS

This PR attempts to fix the incorrect code attribution of vault secrets files to vault-cloud team, and moves them to vault-secrets team.
```sh
...
```

Fix code ownership for vault secrets files

---

.changelog/810.txt
.github/workflows/test-identity.yml
contributing/writing-tests.md
internal/provider/iam/data_group_test.go

This PR aims to improve how identity-specific tests are run.
I've added a comment line in one of the identity files to trigger the test workflow. This of course can't be merged to main so I've removed it now after confirming that the action did indeed run on a change. Reviewers can check the commit history to see the checks that passed when this comment was still present. Specifically this commit: https://github.com/hashicorp/terraform-provider-hcp/actions/runs/8649951887/job/23717371696?pr=810
```sh
>make testacc TEST=./internal/provider/iam
TF_ACC=1 go test ./internal/provider/iam -v  -timeout 360m -parallel=10
=== RUN   TestAccGroupDataSource
--- …
```

HCPIE-1244: Improve Identity-Specific Testing

---

.changelog/812.txt
internal/clients/vault_secrets.go
internal/provider/vaultsecrets/resource_vault_secrets_secret_test.go

This PR does two things:
1. Add retries for HTTP status code 429 errors received on the OpenVaultSecretsAppSecret api.
2. Fixes the already broken `TestAccVaultSecretsResourceSecret` acceptance test.
```sh
Fri Apr 12 11:23:25 EDT 2024 hashicorp/terraform-provider-hcp > make testacc TESTARGS='-run=TestAccVaultSecrets'  
TF_ACC=1 go test ./internal/... -v -run=TestAccVaultSecrets -timeout 360m -parallel=10 -count 1
?       github.com/hashicorp/terraform-provider-hcp/internal/clients/iampolicy  [no test files]
?       github.com/hashicorp/terraform-provider-hcp/internal/clients/packerv2   [no test files]
?       github.com/hashicorp/terraform-provider-hcp/internal/provider   [no test files]
?       github.com/hashicorp/terraform-provider-hcp/internal/provider/a …
```

Gracefully handle rate limiting error on `hcp_vault_secrets_secret` resource.

---

.changelog/820.txt
.github/CODEOWNERS

Fix codeowners for vault secrets resources. The last [attempt](https://github.com/hashicorp/terraform-provider-hcp/pull/814) didn't work as expected. 
```sh
...
```

Fix code owners for vault secrets and vault

---

.changelog/808.txt
docs/resources/vault_secrets_app.md
docs/resources/vault_secrets_secret.md
internal/provider/vaultsecrets/resource_vault_secrets_app.go
internal/provider/vaultsecrets/resource_vault_secrets_app_test.go
internal/provider/vaultsecrets/resource_vault_secrets_secret.go
internal/provider/vaultsecrets/resource_vault_secrets_secret_test.go

This change fixes parts of the [ issue](https://github.com/hashicorp/terraform-provider-hcp/issues/742) where resources are not sensitive to default project ID changes. It also fixes [VAULT-25738](https://hashicorp.atlassian.net/browse/VAULT-25738).
This fix is only for HVS. The other resources that have this issue will be incrementally fixed.
```sh
$  make testacc TESTARGS='-run=TestAccVaultSecretsResourceApp'
TF_ACC=1 go test ./internal/... -v -run=TestAccVaultSecretsResourceApp -timeout 360m -parallel=10
? …
```

HCPF-1673: Fix HVS ignoring default project change.

---

internal/provider/waypoint/resource_waypoint_tfc_config_test.go

NOTE: this PR is opened against the [update-hcp-sdk-093 PR branch](https://github.com/hashicorp/terraform-provider-hcp/pull/823). 
A recent API change was made that changed how the Waypoint service responds to the `GetTFCConfig` endpoint. This PR here is a patch to address a panic that presents in the `TestAccWaypointTfcConfig_basic` test only. The actual `hcp_waypoint_tfc_config` resource functionality is fine, just the test panics right now

Waypoint: Temporary fix for panic due to api change

---

go.mod
go.sum
internal/provider/waypoint/resource_waypoint_tfc_config_test.go

This updates our HCP SDK to https://github.com/hashicorp/hcp-sdk-go/releases/tag/v0.93.0
In addition, this contains a fix to a bug in the Waypoint provider:
A recent API change was made that changed how the Waypoint service responds to the `GetTFCConfig` endpoint. This PR here is a patch to address a panic that presents in the `TestAccWaypointTfcConfig_basic` test only. The actual `hcp_waypoint_tfc_config` resource functionality is fine, just the test panics right now

Bump hcp-sdk-go to 0.93.0, address Waypoint TFCConfig bug

---

.changelog/830.txt
docs/resources/log_streaming_destination.md
templates/resources/log_streaming_destination.md.tmpl

Upgrading the `hcp_log_streaming_destination` resource from private beta to public beta
```sh
...
```

Upgrade hcp_log_streaming_destination resource to public beta

---

.github/workflows/prerelease.yml

Fixing the Prerelease Github Action for scheduled runs. 
After this PR: https://github.com/hashicorp/terraform-provider-hcp/pull/796 , we were still seeing the same error message in the runs [Example](https://github.com/hashicorp/terraform-provider-hcp/actions/runs/8904358607):
```
[Prerelease](https://github.com/hashicorp/terraform-provider-hcp/actions/runs/8904358607/workflow)
The template is not valid. .github/workflows/prerelease.yml (Line: 34, Col: 23): Unexpected value ''
```
Apparently scheduled jobs set all inputs as null ([example 1](https://stackoverflow.com/questions/72539900/schedule-trigger-github-action-workflow-with-input-parameters), [example 2](https://github.com/orgs/community/discussions/74698)), so we need to account for that case.
```sh …
```

Fix skip-e2e-tests flag for Prerelease scheduled runs

---

.changelog/819.txt
docs/data-sources/waypoint_add_on_definition.md
docs/data-sources/waypoint_application_template.md
docs/resources/waypoint_add_on_definition.md
docs/resources/waypoint_application_template.md
internal/provider/waypoint/data_source_waypoint_add_on_definition.go
internal/provider/waypoint/data_source_waypoint_add_on_definition_test.go
internal/provider/waypoint/resource_waypoint_add_on_definition.go
internal/provider/waypoint/resource_waypoint_add_on_definition_test.go
internal/provider/waypoint/resource_waypoint_application_template.go

This PR updates the hcp_waypoint_add_on_definition resource and data source to set and retrieve input variable options for HCP Waypoint add-ons.
```sh
$ make testacc TESTARGS='-run=TestAccWaypoint_Add_On_Definition_basic'
=== RUN   TestAccWaypoint_Add_On_Definition_basic
--- PASS: TestAccWaypoint_Add_On_Definition_basic (8.16s)
$ make testacc TESTARGS='-run=TestAccWaypointData_Add_On_Definition_basic'
=== RUN   TestAccWaypointData_Add_On_Definition_basic
--- PASS: TestAccWaypointData_Add_On_Definition_basic (11.91s)
```

[WAYP-2172] Set variable options for add-on definitions

---

.changelog/838.txt
docs/resources/vault_secrets_app_iam_binding.md
docs/resources/vault_secrets_app_iam_policy.md
internal/provider/vaultsecrets/resource_vault_secrets_app_iam_policy.go
templates/resources/vault_secrets_app_iam_binding.md.tmpl
templates/resources/vault_secrets_app_iam_policy.md.tmpl

- Currently, when we try to create a binding or policy on an HVS App that doesn't have any policy associated with it, the ResourceServiceGetIamPolicy done to fetch the existing call errors out, which bubbles up as an error in the terraform apply. 
- This PR adds handling for the 404 error in this case, to ignore it and allow the subsequent PUT call to proceed
- Also updates the docs to be under HCP Vault Secrets and fixes an example in one of them
```sh
...
```

Add 404 handling from ResourceServiceGetIamPolicy

---

.changelog/839.txt
internal/provider/waypoint/data_source_waypoint_add_on_definition.go
internal/provider/waypoint/resource_waypoint_add_on.go
internal/provider/waypoint/resource_waypoint_add_on_definition.go
internal/provider/waypoint/resource_waypoint_application.go
internal/provider/waypoint/resource_waypoint_application_template.go
internal/provider/waypoint/resource_waypoint_tfc_config.go

Fix an issue with importing existing Waypoint resources. Prior to this commit any `terraform import` for a waypoint resource could fail because the `projectID` value used to look up the resource by ID would be an empty string, causing a failure to look up the existing resource.

fix state import for Waypoint resources

---

.changelog/822.txt
docs/data-sources/waypoint_add_on.md
docs/resources/waypoint_add_on.md
go.mod
go.sum
internal/provider/waypoint/data_source_waypoint_add_on.go
internal/provider/waypoint/resource_waypoint_add_on.go

This updates the `hcp_waypoint_add_on` resource and data source to read Terraform output values, when present.
In addition, it bumps hcp-sdk-go to v0.96.0
To test:
```sh
$ make testacc TESTARGS='-run=TestAccWaypoint_Add_On_basic'
$ make testacc TESTARGS='-run=TestAccWaypointData_Add_On_basic'
```

Add-on resources and data sources now retrieve output values. 

---

docs/resources/waypoint_add_on_definition.md
docs/resources/waypoint_application_template.md
internal/provider/waypoint/resource_waypoint_add_on_definition.go
internal/provider/waypoint/resource_waypoint_application_template.go

This PR updates the variables with options for Waypoint add-on definitions and templates to be a set and not a list, because ordering isn't a concern.

Convert var opts from list to set for add-on definitions & templates

---

.changelog/835.txt
internal/provider/statuspage.go
internal/providersdkv2/statuspage.go

The provider uses these component IDs to show a warning in Terraform plan output if there is a known outage listed on any of the components on the statuspage. This commit adds HCP Boundary to be included when determining if there's an issue with HCP.

Add HCP Boundary to statuspage component IDs

---

.changelog/846.txt
internal/provider/iam/resource_group.go
internal/provider/iam/resource_group_test.go

Allow empty description for hcp_group updates
Why:
* There may be a case where you want to set an empty description for a group where it had a description before.
This change addresses the need by:
* Adding a default value set to an empty string for the description field in the resource schema.
* Use the update mask to explicitly set the fields that are being updated. This is due to the an empty string not being output in the json payload as the model is set to omitempty.
Side effects:
* The Groups PATCH API will now have a case where update mask is used.
Fixes #843
```sh
$ make testacc TESTARGS='-run=TestAccGroupResource'; echo $?
TF_ACC=1 go test …
```

Allow empty description for hcp_group updates

---

.changelog/849.txt
internal/provider/iam/resource_workload_identity_provider.go
internal/provider/iam/resource_workload_identity_provider_test.go

Compute hcp_iam_workload_identity_provider identity description
Why:
* When an hcp_iam_workload_identity_provider description is not configured in a Terraform file, then Terraform returns an error about the state's value of null not matching the provider's return value of "".
This change addresses the need by:
* Add failing test for hcp_iam_workload_identity_provider description not being configured.
* Fix test by configuring the hcp_iam_workload_identity_provider description attribute to be computed.
Fixes #848
```sh
$ make testacc TESTARGS='-run=TestAccWorkloadIdentityProviderResource'
TF_ACC=1 go test ./internal/... -v …
```

Compute unconfigured workload identity description

---

.changelog/850.txt
internal/clients/client.go
internal/clients/vault_secrets.go
internal/clients/vault_secrets_preview.go
internal/provider/vaultsecrets/data_source_vault_secrets_app.go
internal/provider/vaultsecrets/data_source_vault_secrets_secret.go
internal/provider/vaultsecrets/resource_vault_secrets_secret.go

Allows users to fetch rotating secrets using the `hcp_vault_secrets_app` and `hcp_vault_secrets_secret` data sources
`hcp_vault_secrets_app`: keys from complex (rotating) secrets are concatenated in the same pattern we've been using
Given these secrets 
with
```hcl
data "hcp_vault_secrets_app" "example" {
app_name = "sample-app"
}
output "all-secrets" {
value = data.hcp_vault_secrets_app.example.secrets
sensitive = true
}
```
gives (secret values print out to stdout successfully, am not including here)
```
❯ terraform output all-secrets
tomap({
"READ_ME" = ***
"Step1" = ***
"Step2" = ***
"Step3" = ***
"mongodb_atlas_password" = ***
"mongodb_atlas_username" = ***
})
```
For backwards compatibility in the `hcp_vault_secrets_secret`, any rotating secret will be JSON encoded
using the same …

Include rotated secrets for cloud vault secrets VAULT-22307

---

.changelog/871.txt
docs/data-sources/waypoint_add_on.md
docs/data-sources/waypoint_application.md
docs/resources/waypoint_add_on.md
docs/resources/waypoint_application.md
internal/provider/waypoint/data_source_waypoint_add_on.go
internal/provider/waypoint/data_source_waypoint_application.go
internal/provider/waypoint/resource_waypoint_add_on.go
internal/provider/waypoint/resource_waypoint_application.go

This is a small addition to the existing HCP Waypoint Application resource and data source to allow both to read any output values that may be returned when getting an Application.
```sh
$ make testacc TESTARGS='-run=TestAccWaypoint_Application'
=== RUN   TestAccWaypoint_Application_basic
--- PASS: TestAccWaypoint_Application_basic (9.31s)
=== RUN   TestAccWaypoint_Application_DataSource_basic
--- PASS: TestAccWaypoint_Application_DataSource_basic (16.14s)
=== RUN   TestAccWaypoint_Application_DataSource_WithInputVars
--- PASS: TestAccWaypoint_Application_DataSource_WithInputVars (17.89s)
...
```

HCP Waypoint Application resource and data source reads output values

---

.changelog/894.txt
docs/resources/waypoint_add_on_definition.md
docs/resources/waypoint_template.md
internal/provider/waypoint/resource_waypoint_add_on_definition.go
internal/provider/waypoint/resource_waypoint_template.go

This PR fixes a number of Waypoint provider issues identified in internal testing. The main changes are:
- The `readme_markdown_template` attribute is now able to handle both a base64 encoded string and an unencoded string to better match the underlying behavior of the Waypoint API, which accepts both for now. Eventually the ability to provide a base64 encoded version will be deprecated in the API, this change allows users to use both the new and old behavior until then. This change has been made for both the add-on definition and template resources.
- Various smaller documentation improvements to support the above change and to address smaller pieces of feedback recieved.
```sh
$  make testacc TESTARGS='-run=TestAccWaypoint'
=== RUN …
```

HCP Waypoint Readme update to accept unencoded strings

---

.changelog/869.txt
docs/data-sources/waypoint_add_on.md
docs/data-sources/waypoint_template.md
docs/resources/waypoint_add_on.md
docs/resources/waypoint_add_on_definition.md
docs/resources/waypoint_template.md
internal/provider/waypoint/data_source_waypoint_add_on.go
internal/provider/waypoint/data_source_waypoint_add_on_definition.go
internal/provider/waypoint/data_source_waypoint_template.go
internal/provider/waypoint/resource_waypoint_add_on.go
internal/provider/waypoint/resource_waypoint_add_on_definition.go
internal/provider/waypoint/resource_waypoint_add_on_definition_test.go
internal/provider/waypoint/resource_waypoint_add_on_test.go
internal/provider/waypoint/resource_waypoint_application_test.go
internal/provider/waypoint/resource_waypoint_template.go
internal/provider/waypoint/resource_waypoint_template_test.go

The version of a no-code module is being removed from Waypoint templates and add-ons. The pinned version for a no-code module in HCP TF will be used at provision time.

Waypoint: Remove module version

---

.changelog/1052.txt
docs/resources/waypoint_add_on_definition.md
docs/resources/waypoint_template.md
internal/provider/waypoint/resource_waypoint_add_on_definition.go
internal/provider/waypoint/resource_waypoint_add_on_definition_test.go
internal/provider/waypoint/resource_waypoint_add_on_test.go
internal/provider/waypoint/resource_waypoint_application_test.go
internal/provider/waypoint/resource_waypoint_template.go
internal/provider/waypoint/resource_waypoint_template_test.go

Prior to this commit, the template and add-on definition resource required a user to set a full resource for specifying `terraform_cloud_workspace_details`. However, this resource required users to set a `name` which is a value that Waypoint does nothing with. Rather than requiring users to set this field that isn't used in the first place, this pull request instead introduces a `terraform_project_id` field that is required, and will use the add-on or template name for the erroneous field.
Fixes WAYP-2768 WAYP-2769
```sh
...
```

Waypoint: Require TF Project ID to be set, instead of a `terraform_cloud_workspace_details` resource

---

.changelog/1089.txt
docs/data-sources/boundary_cluster.md
docs/resources/boundary_cluster.md
internal/providersdkv2/data_source_boundary_cluster.go
internal/providersdkv2/resource_boundary_cluster.go
internal/providersdkv2/resource_boundary_cluster_test.go

- Updated the `hcp_boundary_cluster` resources & data sources for collecting version information for deployed or existing clusters. 

Add Version Attributes To Boundary Cluster Resource & Data Source

---

.changelog/1093.txt
internal/provider/waypoint/resource_waypoint_template.go

Previously we had deprecated the `terraform_cloud_workspace_details` resource field for the `hcp_waypoint_template` resource. However the field was still being used by our create and update functions, causing an ugly error whenever users attempted to not use the deprecated field. This fixes that by no longer using the deprecated field at all. This closes Waypoint ticket WAYP-2988.
```sh
$ make testacc TESTARGS='-run=TestAccWaypoint_Template'
=== RUN   TestAccWaypoint_Template_basic
--- PASS: TestAccWaypoint_Template_basic (10.31s)
=== RUN   TestAccWaypoint_template_with_variable_options
--- PASS: TestAccWaypoint_template_with_variable_options (6.36s)
```

[Waypoint] Stop using the deprecated terraform cloud workspace name field

---

.changelog/1098.txt
docs/data-sources/waypoint_add_on_definition.md
docs/data-sources/waypoint_template.md
docs/resources/waypoint_add_on_definition.md
docs/resources/waypoint_template.md
go.mod
go.sum
internal/provider/waypoint/data_source_waypoint_add_on_definition.go
internal/provider/waypoint/data_source_waypoint_add_on_definition_test.go
internal/provider/waypoint/data_source_waypoint_template.go
internal/provider/waypoint/data_source_waypoint_template_test.go
internal/provider/waypoint/resource_waypoint_add_on_definition.go
internal/provider/waypoint/resource_waypoint_add_on_definition_test.go
internal/provider/waypoint/resource_waypoint_template.go
internal/provider/waypoint/resource_waypoint_template_test.go

The execution mode and agent pool ID for workspaces created for Waypoint applications and add-ons, based on their respective templates and add-on definitions, is now configurable in HCP Waypoint. This update to the Terraform provider makes it possible to make those configurations via Terraform.
```sh
$ make testacc TESTARGS="-run=TestAccWaypoint"
TF_ACC=1 go test ./internal/... -v -run=TestAccWaypoint -timeout 360m -parallel=10
?   	github.com/hashicorp/terraform-provider-hcp/internal/clients/packerv2	[no test files]
? …
```

Make execution mode configurable for Waypoint templates & add-ons

---

.changelog/1099.txt
docs/resources/waypoint_template.md
internal/provider/waypoint/resource_waypoint_template.go

The `use_module_readme` attribute allows users to elect to use the readme of their Waypoint template's associated Terraform module in place of providing a readme for that template themselves.
This also updates [hcp-sdk-go](https://github.com/hashicorp/hcp-sdk-go) to release 114.
```sh
$ make testacc TESTARGS='-run=TestAccWaypoint_Template'
=== RUN   TestAccWaypoint_Template_basic
--- PASS: TestAccWaypoint_Template_basic (11.73s)
```

[Waypoint] Added useModuleReadme attrubute to Template resource

---

.changelog/1110.txt
go.mod
go.sum
internal/clients/boundary_cluster.go
internal/providersdkv2/resource_boundary_cluster.go

This commit upgrades the hcp-sdk-go dependency to 0.115.0 and addresses a breaking change within the cloud-boundary APIs. Seems that an empty response body will be generated as an empty interface instead of a struct causing compilation errors when attempting to upgrade.

Handle breaking change in boundary client

---

.changelog/1129.txt
docs/resources/vault_radar_integration_jira_connection.md
docs/resources/vault_radar_integration_jira_subscription.md
docs/resources/vault_radar_integration_slack_connection.md
docs/resources/vault_radar_integration_slack_subscription.md
docs/resources/vault_radar_source_github_cloud.md
docs/resources/vault_radar_source_github_enterprise.md
templates/resources/vault_radar_integration_jira_connection.md.tmpl
templates/resources/vault_radar_integration_jira_subscription.md.tmpl
templates/resources/vault_radar_integration_slack_connection.md.tmpl
templates/resources/vault_radar_integration_slack_subscription.md.tmpl
templates/resources/vault_radar_source_github_cloud.md.tmpl
templates/resources/vault_radar_source_github_enterprise.md.tmpl

Fix to the Vault Radar resource documentation templates.
Documents did not have the subcategory set correctly.

fix vault radar docs.

---

.changelog/1134.txt
go.mod
go.sum
internal/clients/vault_radar.go
internal/provider/vaultradar/radar_source.go
internal/provider/vaultradar/resource_radar_source_github_cloud.go
internal/provider/vaultradar/resource_radar_source_github_cloud_test.go
internal/provider/vaultradar/resource_radar_source_github_enterprise.go
internal/provider/vaultradar/resource_radar_source_github_enterprise_test.go

VAULT-32140: Enable updates to Vault Radar source tokens.
> [!NOTE] 
> The test were run from my dev env.
> These AC test will be skipped for CICD because of pre-existing conditions that would be require for the test to succeed. 
> - Requires Project to already setup with Radar Provisioned.
> - Requires a Service Account with an Admin role on the Project.
> - Requires access to a GitHub Enterprise Server Org and a GitHub Cloud Org
> - Requires the following environment variables to be set:
>    - HCP_PROJECT_ID
>    - RADAR_GITHUB_ENTERPRISE_ORGANIZATION
>    - RADAR_GITHUB_ENTERPRISE_DOMAIN
>    - RADAR_GITHUB_ENTERPRISE_TOKEN
>    - RADAR_GITHUB_ENTERPRISE_TOKEN_2
>    - RADAR_GITHUB_CLOUD_ORGANIZATION
>    - RADAR_GITHUB_CLOUD_TOKEN
>    - …

VAULT-32140: Enable updates to Vault Radar source tokens.

---

.changelog/1139.txt
internal/clients/vault_radar.go
internal/provider/vaultradar/integration_subscription.go
internal/provider/vaultradar/resource_radar_integration_jira_connection_test.go
internal/provider/vaultradar/resource_radar_integration_jira_subscription.go
internal/provider/vaultradar/resource_radar_integration_jira_subscription_test.go
internal/provider/vaultradar/resource_radar_integration_slack_connection_test.go
internal/provider/vaultradar/resource_radar_integration_slack_subscription.go
internal/provider/vaultradar/resource_radar_integration_slack_subscription_test.go
internal/provider/vaultradar/resource_radar_source_github_cloud_test.go
internal/provider/vaultradar/resource_radar_source_github_enterprise_test.go

VAULT-32136: Enable updates to Vault Radar integration subscriptions.
> [!NOTE] 
> The test were run from my dev env.
> These AC test will be skipped for CICD because of pre-existing conditions that would be require for the test to succeed. 
> - Requires Project to already setup with Radar Provisioned.
> - Requires a Service Account with an Admin role on the Project.
> - Requires access to a Jira and Slack instances
> - Requires the following environment variables to be set:
>    - HCP_PROJECT_ID
>    - RADAR_INTEGRATION_JIRA_BASE_URL
>    - RADAR_INTEGRATION_JIRA_EMAIL
>    - RADAR_INTEGRATION_JIRA_TOKEN
>    - RADAR_INTEGRATION_JIRA_PROJECT_KEY
>    - RADAR_INTEGRATION_JIRA_ISSUE_TYPE
>    - RADAR_INTEGRATION_JIRA_ASSIGNEE
>    - …

VAULT-32136: Enable updates to Vault Radar integration subscriptions.

---

.changelog/1140.txt
.github/workflows/test-identity.yml
.tool-versions
go.mod
go.sum
internal/clients/group.go
internal/provider/iam/resource_group.go
internal/provider/iam/resource_group_members.go

Adds a retry wrapper around the Groups and Group Member clients. This wrapper uses exponential backoff to handle the retry.
```sh
TF_ACC=1 go test -short -coverprofile=coverage-e2e.out ./internal/provider/iam -v  -timeout 360m -parallel=10
=== RUN   TestAccGroupDataSource
--- PASS: TestAccGroupDataSource (5.34s)
=== RUN   TestAccServicePrincipalDataSource
--- PASS: TestAccServicePrincipalDataSource (2.67s)
=== RUN   TestAccUserPrincipalDataSource
--- PASS: TestAccUserPrincipalDataSource (3.60s)
=== RUN   TestAccGroupIamPolicyResource
--- PASS: TestAccGroupIamPolicyResource (5.77s)
=== RUN …
```

HCPIE-1846: Handle DEADLINE_EXCEEDED Retries for IAM Groups and Group Members

---

docs/data-sources/vault_secrets_dynamic_secret.md
docs/data-sources/vault_secrets_rotating_secret.md
templates/data-sources/vault_secrets_dynamic_secret.md.tmpl
templates/data-sources/vault_secrets_rotating_secret.md.tmpl

The feature are no longer in Beta so we are removing the note in the docs.
Not necessary for a doc PR.

Remove beta tag from HCP vault secrets data sources

---

.github/workflows/prerelease.yml

* This PR disables the automated trigger for Prerelease action (cron schedule) as it will always currently timeout at 6 hours and is creating many hanging resources every time as a result.
```sh
...
```

Disable Prerelease via Cron

---

.changelog/1146.txt
docs/data-sources/waypoint_add_on_definition.md
docs/data-sources/waypoint_template.md
docs/resources/waypoint_add_on_definition.md
docs/resources/waypoint_template.md
internal/provider/waypoint/data_source_waypoint_add_on_definition.go
internal/provider/waypoint/data_source_waypoint_add_on_definition_test.go
internal/provider/waypoint/data_source_waypoint_template.go
internal/provider/waypoint/data_source_waypoint_template_test.go
internal/provider/waypoint/resource_waypoint_add_on_definition.go
internal/provider/waypoint/resource_waypoint_add_on_definition_test.go
internal/provider/waypoint/resource_waypoint_add_on_test.go
internal/provider/waypoint/resource_waypoint_application_test.go
internal/provider/waypoint/resource_waypoint_template.go
internal/provider/waypoint/resource_waypoint_template_test.go

BREAKING CHANGE: The no-code module ID is required when creating a template or add-on definition for Waypoint.
This PR also contains a fix for the add-on definition data source, for reading the execution mode.
```sh
$ make testacc TESTARGS="-run=TestAccWaypoint"
TF_ACC=1 go test ./internal/... -v -run=TestAccWaypoint -timeout 360m -parallel=10
?   	github.com/hashicorp/terraform-provider-hcp/internal/clients/packerv2	[no test files]
?   	github.com/hashicorp/terraform-provider-hcp/internal/customdiags	[no test files]
PASS
ok …
```

[WAYP-3107] Add module ID to Waypoint resources

---

.github/workflows/prerelease.yml
.github/workflows/test.yml
.github/workflows/testacc.yml

* This PR starts laying groundwork for the acceptance test suite, as described in RFC [HCP-483](https://go.hashi.co/rfc/hcp-483), specifically:
1. Updates the `Test` workflow to remove the acceptance test component. This workflow will now only run unit tests and linting.
2. Adds a new workflow, `TestAcc` which acts to orchestrate all the Acceptance test groups (once they exist). Each group (represented by its' own workflow) will have a job and thereby execute in parallel.
3. Updates the `Prerelease` workflow to use the new `TestAcc` workflow so Unit tests and Acceptance tests are still a prerequisite to cutting a release without the option to bypass.

HCPCP-2204: Acceptance Tests - Orchestration

---

.github/workflows/_testacc_vault.yml
internal/providersdkv2/resource_vault_cluster_perf_replication_test.go
internal/providersdkv2/resource_vault_cluster_test.go
internal/providersdkv2/resource_vault_plugin_test.go
internal/providersdkv2/test_helpers_test.go

* This PR onboards the Vault group of Acceptance Tests to be able to run independently of the rest of the suite.
1. Adds a new Actions workflow - `TestAcc - Vault` - which is configured to run on-demand, called by the `TestAcc` workflow, or automatically on PR when any related implementation changes.
2. Utilizes it's own dedicated HCP provider account, by seeding new creds via GH Secrets.
3. Parallelizes the tests, and updates HVN resource names to be unique to support this update.
4. ⚠️ 2 Tests are skipped and will need triage by the cloud vault team. The current errors are outputted for reference in the action run.
```sh
TestAccVaultClusterAWS
TestAccVaultClusterAzure
TestAccVaultPlugin
TestAccPerformanceReplication_ValidationsAws
```
```sh
VAULT_HCP_ORGANIZATION_ID
VAULT_HCP_PROJECT_ID …
```

HCPCP-2204: Acceptance Tests - Vault

---

.github/workflows/_testacc_vault.yml
.github/workflows/prerelease.yml
.github/workflows/test.yml
.github/workflows/testacc.yml

* Error when running `Prerelease` workflow: `Error: Input required and not supplied: token`
* Updates to propagate secrets through called workflows.
* Updates permissions to `write` so actions has permissions to cancel runs.
* Add concurrency (1-at-a-time queue) for `Prerelease` workflow
* https://github.com/hashicorp/terraform-provider-hcp/actions/runs/12815927903/job/35735708817#logs
```sh
...
```

Update action permissions and secrets

---

.changelog/1164.txt
docs/data-sources/boundary_cluster.md
docs/resources/boundary_cluster.md
examples/resources/hcp_boundary_cluster/resource.tf
go.mod
go.sum
internal/clients/boundary_cluster.go
internal/providersdkv2/data_source_boundary_cluster.go
internal/providersdkv2/resource_boundary_cluster.go
internal/providersdkv2/resource_boundary_cluster_test.go

- Added new optional input values for configuring the controller's `auth_token_time_to_live` and `auth_token_time_to_stale` in a valid duration string (following `time.Duration` standards`
-  `auth_token_time_to_live` defaults to `7` days
- `auth_token_time_to_stale` defaults to `1` day
- When specifying either new attribute the other is required along side. 
```sh
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider/webhook/validator (cached) [no tests to run]
=== RUN   TestAccBoundaryCluster
--- PASS: TestAccBoundaryCluster (149.94s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/providersdkv2      150.526s
...
```

Add Controller Config TTLs Options For Boundary Cluster Resource/Data

---

.changelog/1189.txt
docs/resources/vault_secrets_integration.md
go.mod
go.sum
internal/provider/vaultsecrets/resource_vault_secrets_integration.go
internal/provider/vaultsecrets/resource_vault_secrets_integration_test.go
internal/provider/vaultsecrets/vault_secrets_utils.go

This PR adds support for creating GitLab integrations via the HCP provider.
```sh
$ make testacc TESTARGS='-run=TestAccVaultSecretsResourceIntegrationGitLab'
...
```

Add support for GitLab integration

---

.changelog/1181.txt
internal/clients/group.go
internal/clients/project.go
internal/clients/retry_request.go
internal/clients/service_error.go
internal/provider/resourcemanager/resource_project.go

Adds a retry wrapper around projects `create`, `setName` and `setDescription` clients. This wrapper uses exponential backoff to handle the retry.
```sh
$ make testacc TESTARGS='-run=TestAccProjectResource'
TF_ACC=1 go test ./internal/... -v -run=TestAccProjectResource -timeout 360m -parallel=10
?   	github.com/hashicorp/terraform-provider-hcp/internal/clients/packerv2	[no test files]
?   	github.com/hashicorp/terraform-provider-hcp/internal/customdiags	[no test files]
?   	github.com/hashicorp/terraform-provider-hcp/internal/helpers	[no test files]
? …
```

HCPF-2274:  Handle DEADLINE_EXCEEDED Retries for projects create, setName and setDescription

---

.changelog/1207.txt
docs/resources/log_streaming_destination.md
templates/resources/log_streaming_destination.md.tmpl

Marks the `hcp_log_streaming_destination` resource as generally available by removing the public beta note from the docs.

docs: log_streaming_destination GA, remove public beta note

---

.changelog/1157.txt
internal/provider/vaultsecrets/resource_vault_secrets_secret.go
internal/provider/vaultsecrets/resource_vault_secrets_secret_test.go

If you change the name of a hcp_vault_secrets_secret it is expected that the secret with the previous name gets deleted and the a secret with the new name gets created. However, the TF provider treats it as an update and creates the new secret while not deleting the previous one. This change adds a fix for this.
JIRA: https://hashicorp.atlassian.net/browse/HV-3235
```sh
...
```
Local test where I changed the app name and secret name, terraform plan shows 2 to be added and 2 to be destroyed

Add RequiresReplace attribute for secret_name in hvs secret resource

---

.github/workflows/pr-stale.yml

Add stale PR workflow
```sh
...
```

Add stale PR workflow

---

.changelog/1208.txt
docs/data-sources/waypoint_add_on.md
docs/resources/waypoint_add_on.md
internal/clients/client.go
internal/clients/waypoint.go
internal/provider/waypoint/data_source_waypoint_action.go
internal/provider/waypoint/data_source_waypoint_add_on.go
internal/provider/waypoint/data_source_waypoint_add_on_definition.go
internal/provider/waypoint/data_source_waypoint_application.go
internal/provider/waypoint/data_source_waypoint_template.go
internal/provider/waypoint/resource_waypoint_action.go
internal/provider/waypoint/resource_waypoint_add_on.go
internal/provider/waypoint/resource_waypoint_add_on_definition.go
internal/provider/waypoint/resource_waypoint_application.go
internal/provider/waypoint/resource_waypoint_template.go
internal/provider/waypoint/resource_waypoint_tfc_config.go
internal/provider/waypoint/resource_waypoint_tfc_config_test.go

Waypoint API calls are now all made to the new 20241122 version of the API. 
In addition, the CreatedBy resource is now marked as deprecated so that it can be completely removed in a future update to the Waypoint provider.
```sh
$ make testacc TESTARGS='-run=TestAccWaypoint'
=== RUN   TestAccWaypointData_Add_On_Definition_basic
--- PASS: TestAccWaypointData_Add_On_Definition_basic (19.93s)
=== RUN   TestAccWaypointData_Add_On_basic
--- PASS: TestAccWaypointData_Add_On_basic (22.11s)
=== RUN   TestAccWaypoint_AddOn_DataSource_WithInputVars
--- PASS: TestAccWaypoint_AddOn_DataSource_WithInputVars (22.78s)
=== RUN   TestAccWaypoint_Application_DataSource_basic
--- PASS: TestAccWaypoint_Application_DataSource_basic (19.26s)
=== RUN …
```

[WAYP-3244] Switch to new Waypoint API version

---

docs/resources/log_streaming_destination.md
internal/provider/logstreaming/resource_hcp_log_streaming_destination.go

Documents a `log_streaming_destination` resource limitation, streaming to splunk cloud free trial instances is not supported.

docs: streaming to splunk cloud free trials not supported

---

.changelog/1246.txt
internal/provider/resourcemanager/resource_project.go

As per [this ticket](https://hashicorp.atlassian.net/browse/HCPF-2881), we're increasing the timeout on project deletion to allow for a little more wiggle room with this operation as it relies on TFC syncing in the background and in our testing, we have observed that this particular endpoint has been problematic. See the linked Jira ticket for some testing that I did which show the improvement here.
```sh
...
```

Increase project delete timeout

---

internal/provider/provider.go

Remove unused code
```sh
...
```

Remove unused code in the provider

---

docs/data-sources/waypoint_action.md
docs/data-sources/waypoint_add_on.md
docs/data-sources/waypoint_add_on_definition.md
docs/data-sources/waypoint_application.md
docs/data-sources/waypoint_template.md
docs/resources/waypoint_action.md
docs/resources/waypoint_add_on.md
docs/resources/waypoint_add_on_definition.md
docs/resources/waypoint_application.md
docs/resources/waypoint_template.md
docs/resources/waypoint_tfc_config.md
templates/data-sources/waypoint_action.md.tmpl
templates/data-sources/waypoint_add_on.md.tmpl
templates/data-sources/waypoint_add_on_definition.md.tmpl
templates/data-sources/waypoint_application.md.tmpl
templates/data-sources/waypoint_template.md.tmpl
templates/resources/waypoint_action.md.tmpl
templates/resources/waypoint_add_on.md.tmpl
templates/resources/waypoint_add_on_definition.md.tmpl
templates/resources/waypoint_application.md.tmpl
templates/resources/waypoint_template.md.tmpl
templates/resources/waypoint_tfc_config.md.tmpl

- Updated templates and docs to remove the note `-> **Note:** HCP Waypoint is currently in public beta.`.
- Updated the waypoint actions docs to specify that actions is currently in beta.

docs: waypoint actions in beta update

---

.changelog/1270.txt
go.mod
go.sum

This PR has changes to update the `hcp-sdk-go` version to the latest tag

Update hcp-sdk-go version

---

.changelog/1269.txt
internal/providersdkv2/resource_hvn_route_test.go

As a part of [#inc-4707](https://hashicorp.enterprise.slack.com/archives/C08PZKCRXHB) , We had to delete some lingering HVNs and fix `TestAcc_Platform_HvnRouteAzureInvalidConfig` specific case for testing invalid Azure configuration for an HVN route produces the expected error. 
The [prerelease run](https://github.com/hashicorp/terraform-provider-hcp/actions/runs/14727461991/job/41333483204) due to 
`    resource_hvn_route_test.go:509: Step 1/1, expected an error with pattern, no match on: Error running apply: exit status 1
Error: A resource with the ID "/subscriptions/***/resourceGroups/fail" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_resource_group" for more information.
with …

Add unique name for azurerm_role_definition in Azure HVN invalid config test

---

.github/workflows/_testacc_vaultradar.yml

VAULT-37310: Enable ACC for Radar's `data_source_radar_resources_test` and `resource_radar_resource_iam_policy_test`.
Output from running workflow.
https://github.com/hashicorp/terraform-provider-hcp/actions/runs/15861860583/job/44720697922

VAULT-37310: Enable ACC for a few Vault Radar Tests

---

.changelog/1354.txt
docs/index.md
go.mod
go.sum
internal/clients/client.go
internal/clients/client_test.go
internal/provider/provider.go
internal/providersdkv2/provider.go

This PR add a new configurable field to the HCP provider: `geography`. Currently the default is `us` as it depends on `hcp-sdk-go`.
Tested manually with both `us` and `eu`
```
provider "hcp" {
geography = "eu"
}
```
or 
```
provider "hcp" {
geography = "us"
}
```
Invalid value returns errors
```
provider "hcp" {
geography = "ap"
}
│ Error: Invalid Attribute Value Match
│ 
│   with provider["hashicorp.com/test/hcp"],
│   on main.tf line 29, in provider "hcp":
│   29:     geography = "ap"
│ 
│ Attribute geography value must be one of: ["us" "eu"], got: "ap"
```
```sh
...
```
Examples of changes to controls include access controls, encryption, logging, etc.
Examples include changes to operating systems, ports, …

HCPCP-2321 add geography provider schema

---

.changelog/1361.txt
docs/resources/service_principal_key.md
examples/resources/hcp_service_principal_key/resource_rotation.tf

Fixing example code for `hcp_service_principal_key`.

Correct rotate_triggers attribute of hcp_service_principal_key example
