hashicorp/terraform-provider-hcp

.github/PULL_REQUEST_TEMPLATE.md

Add a PR template to include reminders and help guide newcomers
N/A

HCPE-990 - Add PR template

---

internal/clients/client.go
internal/clients/vault_cluster.go

This PR, along with https://github.com/hashicorp/terraform-provider-hcp/pull/84, lay down the foundation for the Vault cluster and admin token resources, coming in follow-up PRs.
⚠️ #84 must merge first.

HCPE-1068: add vault client helpers

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Prep for release of 0.4.1, which includes a patch for the Consul vm size attribute.

0.4.1 patch: update changelog and readme version

---

CHANGELOG.md

Now includes ref to https://github.com/hashicorp/terraform-provider-hcp/pull/108

update CHANGELOG to include fix

---

go.mod
internal/provider/resource_consul_cluster.go

Reverts hashicorp/terraform-provider-hcp#161

Revert "Fix terraform updates for min_consul_version"

---

internal/provider/data_source_consul_cluster.go

We added a new field read for the resource but the data source schema doesn't have that field. We have been re-using the set function for both the data source and the resource. Viewing examples like this:
https://github.com/hashicorp/terraform-provider-aws/blob/3f7d0f8a372b19ed5b35992b04c6aef1562b5473/aws/resource_aws_ami.go#L329
& 
https://github.com/hashicorp/terraform-provider-aws/blob/3f7d0f8a372b19ed5b35992b04c6aef1562b5473/aws/data_source_aws_ami.go#L202
It appears that we should have distinct functions for setting those values since they are technically different schemas.
```
make testacc TESTARGS='-run=TestAccConsulCluster'
TF_ACC=1 go test ./internal/... -v -run=TestAccConsulCluster …
```

Seperate data source attributes from resource set

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
scripts/changelog-links.sh

Made all the PR links work in the Changelog! ☺️ 
(I thought this used to work automatically..? Might just be thinking of PR/release note descriptions)

fix links in changelog

---

docs/resources/consul_cluster.md
templates/resources/consul_cluster.md.tmpl

```release-note
```
```
...
```

Remove beta banner for Plus Tier and Federation

---

docs/guides/consul-federation.md
templates/guides/consul-federation.md.tmpl

This PR explains the restrictions on federation based on the consul cluster tier. https://hashicorp.atlassian.net/browse/HCS-2108
```release-note
```
```
...
```

explain tier restrictions

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Prep for release of 0.11.0!
```
$ make testacc
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	3329.753s
```

update changelog and README version

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Preps the release of v0.16.0 - featuring a dependency bump and doc update!

Prep v0.16.0

---

internal/clients/vault_cluster.go

Fixed a minor typo in which the comments in the Vault client were erroneously refering to Consul.
```release-note
NONE
```
```
...
```

Fix typo in vault cluster comments

---

internal/provider/data_source_packer_image_iteration_test.go

```release-note
* NONE [GH-284]
```
```
$  make testacc TESTARGS='-run=TestAcc_dataSourcePacker'
TF_ACC=1 go test ./internal/... -v -run=TestAcc_dataSourcePacker -timeout 120m
?       github.com/hashicorp/terraform-provider-hcp/internal/clients    [no test files]
PASS
PASS
--- PASS: …
```

Fix HCP Packer acc test - make sure test registry is plus

---

.github/PULL_REQUEST_TEMPLATE.md
contributing/breaking-changes.md

This PR adds some guidance around breaking changes.

TCE-1117: breaking changes guide

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf
go.mod
go.sum

```
$ make testacc TESTARGS='-run=TestAccHvnOnly'
=== RUN   TestAccHvnOnly
--- PASS: TestAccHvnOnly (165.14s)
```

Prep 0.30.0

---

CHANGELOG.md

```
$ make testacc TESTARGS='-run=TestAccHvnOnly'
=== RUN   TestAccHvnOnly
--- PASS: TestAccHvnOnly (165.14s)
```

Followup Prep 0.30.0

---

docs/data-sources/azure_peering_connection.md
docs/index.md
docs/resources/azure_peering_connection.md
docs/resources/consul_cluster.md
internal/provider/resource_hvn_test.go
templates/data-sources/azure_peering_connection.md.tmpl
templates/index.md.tmpl
templates/resources/azure_peering_connection.md.tmpl
templates/resources/consul_cluster.md.tmpl

Some documentation changes to ring in Consul on Azure's public beta :sparkles:

Prep Consul on Azure beta

---

internal/provider/provider.go

Currently, if there are any errors connecting to, or parsing the
response from, status.hashicorp.com, then the provider will crash.
This updates the provider to correctly handle those errors:
```
$ terraform plan
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
+ create
Terraform will perform the following actions:
+ resource "hcp_hvn" "network" {
+ cidr_block          = "10.0.0.0/20"
+ cloud_provider      = "aws"
+ created_at          = (known after apply)
+ hvn_id              = "hcp-hvn-sandbox"
+ id                  = (known after apply)
+ organization_id     = (known after apply)
+ project_id          = (known after apply)
+ provider_account_id = (known after apply)
+ region              = …
```

Fix error handling in isHCPOperational function

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

```
--- PASS: TestAcc_dataSourcePacker (7.25s)
=== RUN   TestAcc_dataSourcePacker_revokedIteration
--- PASS: TestAcc_dataSourcePacker_revokedIteration (10.73s)
=== RUN   TestAcc_dataSourcePackerImage
--- PASS: TestAcc_dataSourcePackerImage (6.50s)
=== RUN   TestAcc_dataSourcePackerImage_revokedIteration
--- PASS: TestAcc_dataSourcePackerImage_revokedIteration (9.77s)
=== RUN   TestAcc_dataSourcePackerIteration
--- PASS: TestAcc_dataSourcePackerIteration (5.12s)
=== RUN   TestAcc_dataSourcePackerIteration_revokedIteration
--- PASS: TestAcc_dataSourcePackerIteration_revokedIteration (10.38s)
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/provider	50.847s
...
```

Prep 0.33.0

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

```release-note
* provider: Bump `hcp-sdk-go` from 0.19.0 to 0.20.0 ([#357](https://github.com/hashicorp/terraform-provider-hcp/pull/357))
* provider: Add retry logic on GET requests when fetching organization and project IDs ([#358](https://github.com/hashicorp/terraform-provider-hcp/pull/358))
```
```
$ make testacc TESTARGS='-run=TestAccVaultCluster'
--- PASS: TestAccVaultCluster (3593.30s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider   3594.034s
...
```

Prep 0.38.0

---

internal/provider/resource_vault_cluster.go

Check type assertions in Vault cluster resource to address https://github.com/hashicorp/terraform-provider-hcp/issues/360.
```release-note
* vault_cluster: Check type assertions to fix issue #360 [GH-364]
```
```
...
```

Check type assertions in Vault cluster resource

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

```
PASS
PASS
PASS
ok  	github.com/hashicorp/terraform-provider-hcp/internal/input	0.177s [no tests to run]
--- PASS: TestAccAwsHvnOnly (129.07s)
```

Prep 0.39.0

---

.github/CODEOWNERS

Replace with the Core SRE team. https://hashicorp.atlassian.net/browse/SRE-1469 [skip ci]
```release-note
NONE
```
```
...
```

The cloud-sre GitHub team is deprecated

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Prep release for 0.41.0
```
PASS
PASS
PASS
--- PASS: TestAccAwsHvnOnly (136.24s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider …
```

Prep 0.41.0

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Release 0.44.0
```release-note
```
```
--- PASS: TestAccAwsPeering (717.15s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider   718.106s
...
```

Release Version 0.44.0

---

go.mod
go.sum
internal/clients/hvn_route.go
internal/clients/operation.go
internal/clients/peering.go
internal/clients/vault_cluster.go
internal/consul/version.go
internal/consul/version_test.go
internal/provider/data_source_aws_network_peering.go
internal/provider/data_source_azure_peering_connection.go
internal/provider/data_source_consul_versions.go
internal/provider/data_source_packer_image_iteration_test.go
internal/provider/resource_boundary_cluster.go
internal/provider/resource_consul_cluster.go
internal/provider/resource_hvn.go
internal/provider/resource_vault_cluster.go

This PR will be reviewed once these changes in the `hcp-sdk-go` are merged in: https://github.com/hashicorp/hcp-sdk-go/pull/122
```release-note
```
```
$ make testacc TESTARGS='-run=TestAccAwsPeering'
--- PASS: TestAccAwsPeering (669.68s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider   670.232s
...
```

Add Fixes for new SDK version based on go-swagger 0.30.2

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Release 0.45.0 of the Terraform Provider.
```release-note
```
```
...
```

Release 0.45.0

---

.changelog/419.txt
.github/workflows/prerelease.yml

Auto update the documentation when a release is triggered.

Auto Release Cleanup: Update Docs on Release

---

.changelog/423.txt
.github/workflows/release.yml

Add a check for the character "v" when compiling the changelog.

Add check for "v" in changelog

---

.changelog/434.txt
docs/guides/auth.md
templates/guides/auth.md.tmpl

This PR updates the auth guide, to be consistent with Go SDK doc updates: https://github.com/hashicorp/hcp-sdk-go/pull/155

update auth guide

---

GNUmakefile
internal/provider/provider_test.go
internal/provider/resource_azure_peering_connection_test.go

Minor acceptance test fixes

---

docs/data-sources/hvn_peering_connection.md
docs/resources/hvn_peering_connection.md
internal/provider/data_source_hvn_peering_connection.go
internal/provider/resource_hvn_peering_connection.go

Add the optional project_id to the HVN Peering Connection resource.

HCE-789: Add project_id to HVN Peering Connection Resource

---

docs/data-sources/aws_transit_gateway_attachment.md
docs/resources/aws_transit_gateway_attachment.md
internal/provider/data_source_aws_transit_gateway_attachment.go
internal/provider/resource_aws_transit_gateway_attachment.go

Add project_id to AWS Transit Gateway Attachment resource

HCE 790 Add project_id to AWS Transit Gateway Attachment Resource

---

docs/data-sources/hvn_route.md
docs/resources/hvn_route.md
internal/provider/data_source_hvn_route.go
internal/provider/resource_hvn_route.go

Add project_id to HVN Route Resource

HCE-791: Add Project ID to HVN Route Resource

---

docs/data-sources/consul_agent_helm_config.md
docs/data-sources/consul_agent_kubernetes_secret.md
docs/data-sources/consul_cluster.md
docs/resources/consul_cluster.md
docs/resources/consul_cluster_root_token.md
docs/resources/consul_snapshot.md
internal/provider/data_source_consul_agent_helm_config.go
internal/provider/data_source_consul_agent_kubernetes_secret.go
internal/provider/data_source_consul_cluster.go
internal/provider/resource_consul_cluster.go
internal/provider/resource_consul_cluster_root_token.go
internal/provider/resource_consul_snapshot.go

Add project_id to Consul Cluster resources.

HCE-792: Add Project ID to Consul Cluster Resource

---

.github/CODEOWNERS

Change code owners to temporary Experiences Platform Transition Pod.

EPT-77: Change Owners to EPT Pod

---

docs/data-sources/boundary_cluster.md
docs/resources/boundary_cluster.md
internal/provider/data_source_boundary_cluster.go
internal/provider/resource_boundary_cluster.go

Add project_id to Boundary Cluster resource.

HCE-794: Add project_id to Boundary Cluster Resource

---

docs/data-sources/packer_image.md
docs/data-sources/packer_iteration.md
docs/resources/packer_channel.md
internal/provider/data_source_packer_image.go
internal/provider/data_source_packer_image_iteration.go
internal/provider/data_source_packer_iteration.go
internal/provider/resource_packer_channel.go

Add project_id to Packer datasources and resources

HCE-795: Add Project ID to Packer

---

docs/guides/multi-project-migration-guide.md
examples/guides/multi_project_migration_guide/no-project.tf
examples/guides/multi_project_migration_guide/project-on-provider.tf
examples/guides/multi_project_migration_guide/project-on-resource.tf
examples/guides/multi_project_migration_guide/resource-override-provider.tf
templates/guides/multi-project-migration-guide.md.tmpl

Adds a guide for the upcoming release of multi projects.

HCE-812: multi-project migration guide

---

.changelog/502.txt
.github/CODEOWNERS

Add `boundary-cloud` team as code owners for any files with `boundary` in the path
```
N/A
```

Add HCP Boundary to CODEOWNERS

---

.github/CODEOWNERS

🎟️ https://hashicorp.atlassian.net/browse/EPT-148

chore(CODEOWNERS): remove EPT

---

.changelog/552.txt
docs/guides/auth.md
docs/index.md
templates/guides/auth.md.tmpl
templates/index.md.tmpl

Updating documentation to take into account usage of the provider with Project level service principals https://developer.hashicorp.com/hcp/docs/hcp/admin/iam/service-principals#project-level-service-principals

updated docs for project level service principals

---

docs/data-sources/vault_secrets_secret.md
internal/provider/data_source_vault_secrets_secret.go

- Add missing `Sensitive: true` on `vault_secrets_secret` data source

Add missing `Sensitive: true` on `vault_secrets_secret` data source

---

.changelog/620.txt

- Adds a changelog for the Documentation Subcategories formatting fixes
- #613 
- #614 
- #615 
- #616 
- #617

Documentation Subcategories Formatting Fix

---

.github/workflows/prerelease.yml

Add support for multiple patch releases in a row

Add support for multiple patch releases in a row

---

docs/guides/vault-secrets-data-sources.md
docs/guides/vault-secrets-resources.md
examples/guides/vault_secrets/datasources.tf
examples/guides/vault_secrets/datasourcesingle.tf
examples/guides/vault_secrets/resourceapp.tf
examples/guides/vault_secrets/resources.tf
templates/guides/vault-secrets-data-sources.md.tmpl
templates/guides/vault-secrets-resources.md.tmpl

Adding guides for Vault Secrets
```
...
```

Adding TF Guides for Vault Secrets

---

.github/CODEOWNERS

- Add codeowner for IAM resources

Add codeowner for IAM resources

---

.github/workflows/terraform_provider.yml
README.md

- Removes a warning for an impending deprecation in v0.75.0 (which has been released)

Remove outdated warning

---

.changelog/687.txt

* Removes a changelog entry which is not needed.
```
...
```

Remove Internal Changelog Entry

---

docs/resources/iam_workload_identity_provider.md
docs/resources/service_principal.md
docs/resources/service_principal_key.md
examples/resources/hcp_iam_workload_identity_provider/resource_aws.tf
examples/resources/hcp_iam_workload_identity_provider/resource_azure.tf
examples/resources/hcp_iam_workload_identity_provider/resource_gcp.tf
internal/provider/iam/resource_service_principal.go
internal/provider/iam/resource_service_principal_key.go
internal/provider/iam/resource_workload_identity_provider.go

Fix Workload Identity Provider examples and description validation.

Fix Workload Identity Provider examples and description validation.

---

docs/resources/log_streaming_destination.md
examples/resources/hcp_log_streaming_destination/resource.tf
internal/provider/logstreaming/resource_hcp_log_streaming_destination.go

- update endpoint in docs with correct format
- update the token attribute to “sensitive” so the TF cli output obscures the token

Update HCP Log Streaming Destination Resource

---

.github/workflows/prerelease.yml

* Prerelease (and subsequent release) is [running at all times](https://github.com/hashicorp/terraform-provider-hcp/actions/runs/7634536838), even when tests are failing.
* Removes the run conditional to not always trigger prerelease job.

Update Prerelease run condition

---

.github/workflows/prerelease.yml

We need this change to release.
Reverts hashicorp/terraform-provider-hcp#733

Revert "Update Prerelease run condition"

---

.github/CODEOWNERS

Make cloud-vault-secrets the code owner of Vault Secrets resources

---

internal/provider/waypoint/resource_waypoint_tfc_config.go
internal/provider/waypoint/resource_waypoint_tfc_config_test.go

Minor refactoring of the Waypoint TFC Config resource to fix a bug with updating. There is duplicated code but it enables updates and added a regression test
```sh
$ ➜ make testacc TESTARGS="-run=TestAccWaypointTfcConfig_basic"
...
```

Hcp waypoint tfc config update

---

.changelog/827.txt
.github/CODEOWNERS

hvs code ownership fix

---

.changelog/847.txt
docs/resources/group_members.md
examples/resources/hcp_group_members/resource.tf

Fix hcp_group_members docs
Why:
* The hcp_user_principal data source exposes a user_id attribute, not an id attribute.
Fixes #821

Fix hcp_group_members docs

---

.changelog/851.txt
go.mod
go.sum
internal/provider/resourcemanager/resource_project.go

Bump hcp-sdk-go to pull in newest changes for upcoming HCP Packer bucket resource
Rename UpdateBillingAccount model with new body model.
```sh
make testacc TESTARGS='-run=TestAccProjectResource'
TF_ACC=1 go test ./internal/... -v -run=TestAccProjectResource -timeout 360m -parallel=10
?   	github.com/hashicorp/terraform-provider-hcp/internal/clients/packerv2	[no test files]
PASS
PASS
ok …
```

Bump hcp-go-sdk and fix billing model name change

---

.changelog/1066.txt
docs/index.md
templates/index.md.tmpl

Updating docs with API accessed by the provider

Update index.md with APIs the provider uses

---

.changelog/1080.txt
go.mod
go.sum
internal/clients/vault_secrets_preview.go

update hcp-sdk-go and breaking change w/ hvs api

---

.goreleaser.yml

Include license file while releasing
```sh
...
```

chore: include license file

---

.changelog/1102.txt
.github/CODEOWNERS

Add vault radar to codeowners file.

Update codeowners with vault radar.

---

.github/workflows/prerelease.yml

* Error encountered during [prerelease](https://github.com/hashicorp/terraform-provider-hcp/actions/runs/11224098330/job/31200254303#step:7:69)
* Installs terraform for prerelease action.
```sh
...
```

Add terraform install to prerelease

---

.changelog/1126.txt
internal/provider/vaultsecrets/rotating_secret_mongodb_atlas.go

mongo should use mongo request structures
```sh
...
```

replace twilio with mongo

---

.github/CODEOWNERS

chore: increase codeowner coverage

---

.github/workflows/prerelease.yml
.github/workflows/testacc.yml

Fix error to unblock release process.
```sh
...
```

Fix release

---

.github/workflows/prerelease.yml

* Requested permission for Test workflow didn't match Prerelease.
```sh
...
```

Adjust prerelease permissions

---

.github/workflows/prerelease.yml

* We need the acceptance tests to be required for Prerelease to proceed to create a release.
```sh
...
```

Make Acceptance Tests a dependency for Prerelease

---

CHANGELOG.md
docs/index.md
examples/provider/provider.tf

Revert half-bake release

---

docs/resources/waypoint_template.md
internal/provider/waypoint/resource_waypoint_template.go

Fix a doc string type and re-generate the docs.
N/A
N/A

Waypoint: Fix typo `odule` -> `module`

---

docs/resources/service_principal_key.md

```sh
...
```
Examples of changes to controls include access controls, encryption, logging, etc.
Examples include changes to operating systems, ports, protocols, services, cryptography-related components, PII processing code, etc.

fix missing go generate

---

.github/CODEOWNERS

* Regenerates documentation for failing CI check
```sh
...
```
Examples of changes to controls include access controls, encryption, logging, etc.
Examples include changes to operating systems, ports, protocols, services, cryptography-related components, PII processing code, etc.

HCPF-3181: update CODEOWNERS for resourcemanager
